from typing import Dict, List, NamedTuple


stage_names = [
    "Viridian Forest",
    "Pewter City",
    "Mt Moon",
    "Cerulean City",
    "Vermilion City Seaside",
    "Vermilion City Streets",
    "Rock Mountain",
    "Lavender Town",
    "Cycling Road",
    "Safari Zone",
    "Fuchsia City",
    "Saffron City",
    "Seafoam Islands",
    "Cinnabar Island",
    "Indigo Plateau"
]


class PokePinballRegionData(NamedTuple):
    connecting_regions: List[str] = []

region_data_table: Dict[str, PokePinballRegionData] = {
    "Menu": PokePinballRegionData(["Red Table", "Blue Table"]),
    "Red Table": PokePinballRegionData([
        "Pallet Town",
        "Viridian Forest",
        "Pewter City",
        "Cerulean City",
        "Vermilion City Seaside",
        "Rock Mountain",
        "Lavender Town",
        "Cycling Road",
        "Safari Zone",
        "Seafoam Islands",
        "Cinnabar Island",
        "Indigo Plateau"]),
    "Blue Table": PokePinballRegionData([
        "Viridian City",
        "Viridian Forest",
        "Mt Moon",
        "Cerulean City",
        "Vermilion City Streets",
        "Rock Mountain",
        "Celadon City",
        "Safari Zone",
        "Fuchsia City",
        "Saffron City",
        "Cinnabar Island",
        "Indigo Plateau"]),

    "Pallet Town": PokePinballRegionData(["Bulbasaur","Charmander","Pidgey","Rattata","Nidoran Male","Poliwag","Tentacool"]),
    "Viridian City": PokePinballRegionData(["Bulbasaur","Squirtle","Spearow","Nidoran Female","Nidoran Male","Poliwag","Tentacool","Goldeen"]),
    "Viridian Forest": PokePinballRegionData(["Caterpie","Weedle","Pidgey","Rattata","Pikachu"]),
    "Pewter City": PokePinballRegionData(["Pidgey","Spearow","Ekans","Jigglypuff","Magikarp"]),
    "Mt Moon": PokePinballRegionData(["Rattata","Spearow","Ekans","Sandshrew","Clefairy","Zubat","Paras","Psyduck","Geodude","Krabby","Goldeen"]),
    "Cerulean City": PokePinballRegionData(["Caterpie","Weedle","Nidoran Male","Oddish","Psyduck","Mankey","Abra","Krabby","Goldeen","Jynx", "Meowth","Bellsprout"]),
    "Vermilion City Seaside": PokePinballRegionData(["Pidgey","Spearow","Ekans","Oddish","Mankey","Farfetchd","Shellder","Drowzee","Krabby"]),
    "Vermilion City Streets": PokePinballRegionData(["Pidgey","Spearow","Sandshrew","Meowth","Bellsprout","Farfetchd", "Shellder","Drowzee","Krabby"]),
    "Rock Mountain": PokePinballRegionData(["Rattata","Spearow","Ekans","Zubat","Diglett","Machop","Geodude","Slowpoke","Onix","Voltorb","Mr Mime"]),
    "Lavender Town": PokePinballRegionData(["Ekans","Mankey","Growlithe","Magnemite","Gastly","Cubone","Electabuzz","Zapdos"]),
    "Celadon City": PokePinballRegionData(["Pidgey","Vulpix","Oddish","Meowth","Mankey","Growlithe","Bellsprout","Abra","Scyther","Pinsir","Eevee","Porygon","Dratini"]),
    "Cycling Road": PokePinballRegionData(["Rattata","Spearow","Tentacool","Doduo","Krabby","Lickitung","Goldeen","Magikarp","Snorlax"]),
    "Fuchsia City": PokePinballRegionData(["Venonat","Krabby","Exeggcute","Kangaskhan","Goldeen","Magikarp"]),
    "Safari Zone": PokePinballRegionData(["Nidoran Male","Paras","Doduo","Rhyhorn","Chansey","Scyther","Tauros","Dratini", "Nidoran Female","Pinsir"]),
    "Saffron City": PokePinballRegionData(["Pidgey","Ekans","Sandshrew","Vulpix","Oddish","Meowth","Mankey","Growlithe","Hitmonlee","Hitmonchan","Lapras"]),
    "Seafoam Islands": PokePinballRegionData(["Zubat","Psyduck","Tentacool","Slowpoke","Seel","Shellder","Krabby","Horsea","Goldeen","Staryu","Articuno"]),
    "Cinnabar Island": PokePinballRegionData(["Vulpix","Growlithe","Ponyta","Omanyte","Kabuto", "Koffing","Grimer","Tangela","Magmar","Aerodactyl"]),
    "Indigo Plateau": PokePinballRegionData([
        "Spearow","Ekans","Zubat","Sandshrew","Machop","Geodude","Onix",
        "Ditto","Moltres","Mewtwo","Mew"]),

    "Bulbasaur": PokePinballRegionData(["Pallet Town","Viridian City",]),
    "Charmander": PokePinballRegionData(["Pallet Town",]),
    "Squirtle": PokePinballRegionData(["Viridian City",]),
    "Caterpie": PokePinballRegionData(["Viridian Forest","Cerulean City",]),
    "Weedle": PokePinballRegionData(["Viridian Forest","Cerulean City",]),
    "Pidgey": PokePinballRegionData(["Pallet Town","Viridian Forest","Pewter City","Vermilion City Seaside",
        "Vermilion City Streets","Celadon City","Saffron City",]),
    "Rattata": PokePinballRegionData(["Pallet Town","Viridian Forest","Mt Moon","Rock Mountain",
            "Cycling Road",]),
    "Spearow": PokePinballRegionData(["Viridian City","Pewter City","Mt Moon","Vermilion City Seaside",
        "Vermilion City Streets","Rock Mountain","Cycling Road","Indigo Plateau",]),
    "Ekans": PokePinballRegionData(["Pewter City","Mt Moon","Vermilion City Seaside","Rock Mountain",
        "Lavender Town","Saffron City","Indigo Plateau",]),
    "Pikachu": PokePinballRegionData(["Viridian Forest",]),
    "Sandshrew": PokePinballRegionData(["Mt Moon","Vermilion City Streets","Saffron City","Indigo Plateau",]),
    "Nidoran Female": PokePinballRegionData(["Viridian City","Safari Zone",]),
    "Nidoran Male": PokePinballRegionData(["Pallet Town","Viridian City","Cerulean City","Safari Zone",]),
    "Clefairy": PokePinballRegionData(["Mt Moon",]),
    "Vulpix": PokePinballRegionData(["Celadon City","Saffron City","Cinnabar Island",]),
    "Jigglypuff": PokePinballRegionData(["Pewter City",]),
    "Zubat": PokePinballRegionData(["Mt Moon","Rock Mountain","Seafoam Islands","Indigo Plateau",]),
    "Oddish": PokePinballRegionData(["Cerulean City","Vermilion City Seaside","Celadon City","Saffron City",]),
    "Paras": PokePinballRegionData(["Mt Moon","Safari Zone",]),
    "Venonat": PokePinballRegionData(["Fuchsia City",]),
    "Diglett": PokePinballRegionData(["Rock Mountain",]),
    "Meowth": PokePinballRegionData(["Cerulean City","Vermilion City Streets","Celadon City","Saffron City",]),
    "Psyduck": PokePinballRegionData(["Mt Moon","Cerulean City","Seafoam Islands",]),
    "Mankey": PokePinballRegionData(["Cerulean City","Vermilion City Seaside","Lavender Town","Celadon City","Saffron City",]),
    "Growlithe": PokePinballRegionData(["Lavender Town","Celadon City","Saffron City","Cinnabar Island",]),
    "Poliwag": PokePinballRegionData(["Pallet Town","Viridian City",]),
    "Abra": PokePinballRegionData(["Cerulean City","Celadon City",]),
    "Machop": PokePinballRegionData(["Rock Mountain","Indigo Plateau",]),
    "Bellsprout": PokePinballRegionData(["Cerulean City","Vermilion City Streets","Celadon City",]),
    "Tentacool": PokePinballRegionData(["Pallet Town","Viridian City","Cycling Road","Seafoam Islands",]),
    "Geodude": PokePinballRegionData(["Mt Moon","Rock Mountain","Indigo Plateau",]),
    "Ponyta": PokePinballRegionData(["Cinnabar Island",]),
    "Slowpoke": PokePinballRegionData(["Rock Mountain","Seafoam Islands",]),
    "Magnemite": PokePinballRegionData(["Lavender Town",]),
    "Farfetchd": PokePinballRegionData(["Vermilion City Seaside","Vermilion City Streets",]),
    "Doduo": PokePinballRegionData(["Cycling Road","Safari Zone",]),
    "Seel": PokePinballRegionData(["Seafoam Islands",]),
    "Grimer": PokePinballRegionData(["Cinnabar Island",]),
    "Shellder": PokePinballRegionData(["Vermilion City Seaside","Vermilion City Streets","Seafoam Islands",]),
    "Gastly": PokePinballRegionData(["Lavender Town",]),
    "Onix": PokePinballRegionData(["Rock Mountain","Indigo Plateau",]),
    "Drowzee": PokePinballRegionData(["Vermilion City Seaside","Vermilion City Streets",]),
    "Krabby": PokePinballRegionData(["Mt Moon","Cerulean City","Vermilion City Seaside","Vermilion City Streets","Cycling Road","Fuchsia City","Seafoam Islands",]),
    "Voltorb": PokePinballRegionData(["Rock Mountain",]),
    "Exeggcute": PokePinballRegionData(["Fuchsia City",]),
    "Cubone": PokePinballRegionData(["Lavender Town",]),
    "Hitmonlee": PokePinballRegionData(["Saffron City",]),
    "Hitmonchan": PokePinballRegionData(["Saffron City",]),
    "Lickitung": PokePinballRegionData(["Cycling Road",]),
    "Koffing": PokePinballRegionData(["Cinnabar Island",]),
    "Rhyhorn": PokePinballRegionData(["Safari Zone",]),
    "Chansey": PokePinballRegionData(["Safari Zone",]),
    "Tangela": PokePinballRegionData(["Cinnabar Island",]),
    "Kangaskhan": PokePinballRegionData(["Fuchsia City",]),
    "Horsea": PokePinballRegionData(["Seafoam Islands",]),
    "Goldeen": PokePinballRegionData(["Viridian City","Mt Moon","Cerulean City","Cycling Road","Fuchsia City","Seafoam Islands",]),
    "Staryu": PokePinballRegionData(["Seafoam Islands",]),
    "Mr Mime": PokePinballRegionData(["Rock Mountain",]),
    "Scyther": PokePinballRegionData(["Celadon City","Safari Zone",]),
    "Jynx": PokePinballRegionData(["Cerulean City",]),
    "Electabuzz": PokePinballRegionData(["Lavender Town",]),
    "Magmar": PokePinballRegionData(["Cinnabar Island",]),
    "Pinsir": PokePinballRegionData(["Celadon City","Safari Zone",]),
    "Tauros": PokePinballRegionData(["Safari Zone",]),
    "Magikarp": PokePinballRegionData(["Pewter City","Cycling Road","Fuchsia City",]),
    "Lapras": PokePinballRegionData(["Saffron City",]),
    "Ditto": PokePinballRegionData(["Indigo Plateau",]),
    "Eevee": PokePinballRegionData(["Celadon City",]),
    "Porygon": PokePinballRegionData(["Celadon City",]),
    "Omanyte": PokePinballRegionData(["Cinnabar Island",]),
    "Kabuto": PokePinballRegionData(["Cinnabar Island",]),
    "Aerodactyl": PokePinballRegionData(["Cinnabar Island",]),
    "Snorlax": PokePinballRegionData(["Cycling Road",]),
    "Articuno": PokePinballRegionData(["Seafoam Islands",]),
    "Zapdos": PokePinballRegionData(["Lavender Town",]),
    "Moltres": PokePinballRegionData(["Indigo Plateau",]),
    "Dratini": PokePinballRegionData(["Celadon City","Safari Zone",]),
    "Mewtwo": PokePinballRegionData(["Indigo Plateau",]),
    "Mew": PokePinballRegionData(["Indigo Plateau",]),
}

def get_exit(region, exit_name):
    for exit in region.exits:
        if exit.connected_region.name == exit_name:
            return exit