MON_ID = {
    "NONE":	0x0,
    "BULBASAUR":	0x1,
    "IVYSAUR":	0x2,
    "VENUSAUR":	0x3,
    "CHARMANDER":	0x4,
    "CHARMELEON":	0x5,
    "CHARIZARD":	0x6,
    "SQUIRTLE":	0x7,
    "WARTORTLE":	0x8,
    "BLASTOISE":	0x9,
    "CATERPIE":	0xa,
    "METAPOD":	0xb,
    "BUTTERFREE":	0xc,
    "WEEDLE":	0xd,
    "KAKUNA":	0xe,
    "BEEDRILL":	0xf,
    "PIDGEY":	0x10,
    "PIDGEOTTO":	0x11,
    "PIDGEOT":	0x12,
    "RATTATA":	0x13,
    "RATICATE":	0x14,
    "SPEAROW":	0x15,
    "FEAROW":	0x16,
    "EKANS":	0x17,
    "ARBOK":	0x18,
    "PIKACHU":	0x19,
    "RAICHU":	0x1a,
    "SANDSHREW":	0x1b,
    "SANDSLASH":	0x1c,
    "NIDORAN_F":	0x1d,
    "NIDORINA":	0x1e,
    "NIDOQUEEN":	0x1f,
    "NIDORAN_M":	0x20,
    "NIDORINO":	0x21,
    "NIDOKING":	0x22,
    "CLEFAIRY":	0x23,
    "CLEFABLE":	0x24,
    "VULPIX":	0x25,
    "NINETALES":	0x26,
    "JIGGLYPUFF":	0x27,
    "WIGGLYTUFF":	0x28,
    "ZUBAT":	0x29,
    "GOLBAT":	0x2a,
    "ODDISH":	0x2b,
    "GLOOM":	0x2c,
    "VILEPLUME":	0x2d,
    "PARAS":	0x2e,
    "PARASECT":	0x2f,
    "VENONAT":	0x30,
    "VENOMOTH":	0x31,
    "DIGLETT":	0x32,
    "DUGTRIO":	0x33,
    "MEOWTH":	0x34,
    "PERSIAN":	0x35,
    "PSYDUCK":	0x36,
    "GOLDUCK":	0x37,
    "MANKEY":	0x38,
    "PRIMEAPE":	0x39,
    "GROWLITHE":	0x3a,
    "ARCANINE":	0x3b,
    "POLIWAG":	0x3c,
    "POLIWHIRL":	0x3d,
    "POLIWRATH":	0x3e,
    "ABRA":	0x3f,
    "KADABRA":	0x40,
    "ALAKAZAM":	0x41,
    "MACHOP":	0x42,
    "MACHOKE":	0x43,
    "MACHAMP":	0x44,
    "BELLSPROUT":	0x45,
    "WEEPINBELL":	0x46,
    "VICTREEBEL":	0x47,
    "TENTACOOL":	0x48,
    "TENTACRUEL":	0x49,
    "GEODUDE":	0x4a,
    "GRAVELER":	0x4b,
    "GOLEM":	0x4c,
    "PONYTA":	0x4d,
    "RAPIDASH":	0x4e,
    "SLOWPOKE":	0x4f,
    "SLOWBRO":	0x50,
    "MAGNEMITE":	0x51,
    "MAGNETON":	0x52,
    "FARFETCH_D":	0x53,
    "DODUO":	0x54,
    "DODRIO":	0x55,
    "SEEL":	0x56,
    "DEWGONG":	0x57,
    "GRIMER":	0x58,
    "MUK":	0x59,
    "SHELLDER":	0x5a,
    "CLOYSTER":	0x5b,
    "GASTLY":	0x5c,
    "HAUNTER":	0x5d,
    "GENGAR":	0x5e,
    "ONIX":	0x5f,
    "DROWZEE":	0x60,
    "HYPNO":	0x61,
    "KRABBY":	0x62,
    "KINGLER":	0x63,
    "VOLTORB":	0x64,
    "ELECTRODE":	0x65,
    "EXEGGCUTE":	0x66,
    "EXEGGUTOR":	0x67,
    "CUBONE":	0x68,
    "MAROWAK":	0x69,
    "HITMONLEE":	0x6a,
    "HITMONCHAN":	0x6b,
    "LICKITUNG":	0x6c,
    "KOFFING":	0x6d,
    "WEEZING":	0x6e,
    "RHYHORN":	0x6f,
    "RHYDON":	0x70,
    "CHANSEY":	0x71,
    "TANGELA":	0x72,
    "KANGASKHAN":	0x73,
    "HORSEA":	0x74,
    "SEADRA":	0x75,
    "GOLDEEN":	0x76,
    "SEAKING":	0x77,
    "STARYU":	0x78,
    "STARMIE":	0x79,
    "MR_MIME":	0x7a,
    "SCYTHER":	0x7b,
    "JYNX":	0x7c,
    "ELECTABUZZ":	0x7d,
    "MAGMAR":	0x7e,
    "PINSIR":	0x7f,
    "TAUROS":	0x80,
    "MAGIKARP":	0x81,
    "GYARADOS":	0x82,
    "LAPRAS":	0x83,
    "DITTO":	0x84,
    "EEVEE":	0x85,
    "VAPOREON":	0x86,
    "JOLTEON":	0x87,
    "FLAREON":	0x88,
    "PORYGON":	0x89,
    "OMANYTE":	0x8a,
    "OMASTAR":	0x8b,
    "KABUTO":	0x8c,
    "KABUTOPS":	0x8d,
    "AERODACTYL":	0x8e,
    "SNORLAX":	0x8f,
    "ARTICUNO":	0x90,
    "ZAPDOS":	0x91,
    "MOLTRES":	0x92,
    "DRATINI":	0x93,
    "DRAGONAIR":	0x94,
    "DRAGONITE":	0x95,
    "MEWTWO":	0x96,
    "MEW":	0x97
}


ENCOUNTER_DATA = {
    0x112cc:[ # PalletTownWildMons
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["CHARMANDER"],
        MON_ID["CHARMANDER"],
        MON_ID["CHARMANDER"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["TENTACOOL"],
        MON_ID["TENTACOOL"],
    ],
    0x112dc:[ # PalletTownWildMonsRare
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["CHARMANDER"],
        MON_ID["CHARMANDER"],
        MON_ID["CHARMANDER"],
        MON_ID["CHARMANDER"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
    ],
    0x112ec: [ # ViridianForestWildMons
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["PIKACHU"],
    ],
    0x112fc: [ # ViridianForestWildMonsRare
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["RATTATA"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
    ],
    0x1130c: [ # PewterCityWildMons
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["SPEAROW"],
        MON_ID["SPEAROW"],
        MON_ID["SPEAROW"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
    ],
    0x1131c: [ # PewterCityWildMonsRare
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["JIGGLYPUFF"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
    ],
    0x1132c: [ # CeruleanCityWildMons
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["ODDISH"],
        MON_ID["ODDISH"],
        MON_ID["PSYDUCK"],
        MON_ID["PSYDUCK"],
        MON_ID["MANKEY"],
        MON_ID["MANKEY"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
    ],
    0x1133c: [ # CeruleanCityWildMonsRare
        MON_ID["CATERPIE"],
        MON_ID["NIDORAN_M"],
        MON_ID["ODDISH"],
        MON_ID["PSYDUCK"],
        MON_ID["PSYDUCK"],
        MON_ID["MANKEY"],
        MON_ID["MANKEY"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["KRABBY"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["JYNX"],
        MON_ID["JYNX"],
        MON_ID["JYNX"],
    ],
    0x1134c: [ # VermilionSeasideWildMons
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["SPEAROW"],
        MON_ID["SPEAROW"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["ODDISH"],
        MON_ID["ODDISH"],
        MON_ID["MANKEY"],
        MON_ID["MANKEY"],
        MON_ID["SHELLDER"],
        MON_ID["SHELLDER"],
        MON_ID["DROWZEE"],
        MON_ID["DROWZEE"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
    ],
    0x1135c: [ # VermilionSeasideWildMonsRare
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["ODDISH"],
        MON_ID["MANKEY"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["SHELLDER"],
        MON_ID["SHELLDER"],
        MON_ID["DROWZEE"],
        MON_ID["DROWZEE"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
    ],
    0x1136c: [ # RockMountainWildMons
        MON_ID["RATTATA"],
        MON_ID["SPEAROW"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["DIGLETT"],
        MON_ID["DIGLETT"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["SLOWPOKE"],
        MON_ID["SLOWPOKE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["VOLTORB"],
        MON_ID["VOLTORB"],
    ],
    0x1137c: [ # RockMountainWildMonsRare
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["DIGLETT"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["SLOWPOKE"],
        MON_ID["SLOWPOKE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["VOLTORB"],
        MON_ID["VOLTORB"],
        MON_ID["MR_MIME"],
        MON_ID["MR_MIME"],
        MON_ID["MR_MIME"],
    ],
    0x1138c: [ # LavenderTownWildMons
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["MANKEY"],
        MON_ID["MANKEY"],
        MON_ID["GROWLITHE"],
        MON_ID["GROWLITHE"],
        MON_ID["MAGNEMITE"],
        MON_ID["MAGNEMITE"],
        MON_ID["ELECTABUZZ"],
        MON_ID["GASTLY"],
        MON_ID["GASTLY"],
        MON_ID["GASTLY"],
        MON_ID["CUBONE"],
        MON_ID["CUBONE"],
    ],
    0x1139c: [ # LavenderTownWildMonsRare
        MON_ID["EKANS"],
        MON_ID["MANKEY"],
        MON_ID["GROWLITHE"],
        MON_ID["MAGNEMITE"],
        MON_ID["MAGNEMITE"],
        MON_ID["GASTLY"],
        MON_ID["GASTLY"],
        MON_ID["CUBONE"],
        MON_ID["CUBONE"],
        MON_ID["CUBONE"],
        MON_ID["ELECTABUZZ"],
        MON_ID["ELECTABUZZ"],
        MON_ID["ELECTABUZZ"],
        MON_ID["ZAPDOS"],
        MON_ID["ZAPDOS"],
        MON_ID["ZAPDOS"],
    ],
    0x113ac: [ # CyclingRoadWildMons
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["SPEAROW"],
        MON_ID["SNORLAX"],
        MON_ID["TENTACOOL"],
        MON_ID["TENTACOOL"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["LICKITUNG"],
        MON_ID["LICKITUNG"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
    ],
    0x113bc: [ # CyclingRoadWildMonsRare
        MON_ID["TENTACOOL"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["KRABBY"],
        MON_ID["LICKITUNG"],
        MON_ID["LICKITUNG"],
        MON_ID["LICKITUNG"],
        MON_ID["LICKITUNG"],
        MON_ID["GOLDEEN"],
        MON_ID["MAGIKARP"],
        MON_ID["SNORLAX"],
        MON_ID["SNORLAX"],
        MON_ID["SNORLAX"],
    ],
    0x113cc: [ # SafariZoneWildMons
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["RHYHORN"],
        MON_ID["RHYHORN"],
        MON_ID["CHANSEY"],
        MON_ID["SCYTHER"],
        MON_ID["DRATINI"],
    ],
    0x113dc: [ # SafariZoneWildMonsRare
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["RHYHORN"],
        MON_ID["RHYHORN"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["SCYTHER"],
        MON_ID["SCYTHER"],
        MON_ID["TAUROS"],
        MON_ID["TAUROS"],
        MON_ID["DRATINI"],
        MON_ID["DRATINI"],
    ],
    0x113ec: [ # SeafoamIslandsWildMons
        MON_ID["ZUBAT"],
        MON_ID["PSYDUCK"],
        MON_ID["TENTACOOL"],
        MON_ID["SLOWPOKE"],
        MON_ID["SEEL"],
        MON_ID["SEEL"],
        MON_ID["SHELLDER"],
        MON_ID["SHELLDER"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["HORSEA"],
        MON_ID["HORSEA"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["STARYU"],
        MON_ID["STARYU"],
    ],
    0x113fc: [ # SeafoamIslandsWildMonsRare
        MON_ID["SEEL"],
        MON_ID["SEEL"],
        MON_ID["SEEL"],
        MON_ID["SEEL"],
        MON_ID["SEEL"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["STARYU"],
        MON_ID["STARYU"],
        MON_ID["STARYU"],
        MON_ID["STARYU"],
        MON_ID["ARTICUNO"],
        MON_ID["ARTICUNO"],
        MON_ID["ARTICUNO"],
    ],
    0x1140c: [ # CinnabarIslandWildMons
        MON_ID["GROWLITHE"],
        MON_ID["GROWLITHE"],
        MON_ID["GROWLITHE"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["GRIMER"],
        MON_ID["GRIMER"],
        MON_ID["GRIMER"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
        MON_ID["OMANYTE"],
        MON_ID["KABUTO"],
    ],
    0x1141c: [ # CinnabarIslandWildMonsRare
        MON_ID["GROWLITHE"],
        MON_ID["GROWLITHE"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["GRIMER"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
        MON_ID["OMANYTE"],
        MON_ID["OMANYTE"],
        MON_ID["OMANYTE"],
        MON_ID["KABUTO"],
        MON_ID["KABUTO"],
        MON_ID["KABUTO"],
    ],
    0x1142c: [ # IndigoPlateauWildMons
        MON_ID["SPEAROW"],
        MON_ID["EKANS"],
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
    ],
    0x1143c: [ # IndigoPlateauWildMonsRare
        MON_ID["SPEAROW"],
        MON_ID["EKANS"],
        MON_ID["ZUBAT"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["ONIX"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["MOLTRES"],
        MON_ID["MOLTRES"],
        MON_ID["MOLTRES"],
        MON_ID["MEWTWO"],
        MON_ID["MEWTWO"],
        MON_ID["MEWTWO"],
        MON_ID["MEW"],
    ],
    # Blue Board
    0x1144d: [ # ViridianCityWildMons
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["SQUIRTLE"],
        MON_ID["SQUIRTLE"],
        MON_ID["SPEAROW"],
        MON_ID["SPEAROW"],
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["TENTACOOL"],
        MON_ID["TENTACOOL"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
    ],
    0x1145d: [ # ViridianCityWildMonsRare
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["BULBASAUR"],
        MON_ID["SQUIRTLE"],
        MON_ID["SPEAROW"],
        MON_ID["SPEAROW"],
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_M"],
        MON_ID["NIDORAN_M"],
        MON_ID["POLIWAG"],
        MON_ID["POLIWAG"],
        MON_ID["TENTACOOL"],
        MON_ID["TENTACOOL"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
    ],
    0x1146d: [ # ViridianForestWildMons
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["WEEDLE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["WEEDLE"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
    ],
    0x1147d: [ # ViridianForestWildMonsRare
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["WEEDLE"],
        MON_ID["WEEDLE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["RATTATA"],
        MON_ID["RATTATA"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
        MON_ID["PIKACHU"],
    ],
    0x1148d: [ # MtMoonWildMons
        MON_ID["RATTATA"],
        MON_ID["SPEAROW"],
        MON_ID["CLEFAIRY"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["PSYDUCK"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["KRABBY"],
        MON_ID["GOLDEEN"],
    ],
    0x1149d: [ # MtMoonWildMonsRare
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
    ],
    0x114ad: [ # CeruleanCityWildMons
        MON_ID["CATERPIE"],
        MON_ID["CATERPIE"],
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["MEOWTH"],
        MON_ID["MEOWTH"],
        MON_ID["PSYDUCK"],
        MON_ID["PSYDUCK"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["BELLSPROUT"],
        MON_ID["BELLSPROUT"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
    ],
    0x114bd: [ # CeruleanCityWildMonsRare
        MON_ID["WEEDLE"],
        MON_ID["NIDORAN_M"],
        MON_ID["MEOWTH"],
        MON_ID["MEOWTH"],
        MON_ID["PSYDUCK"],
        MON_ID["PSYDUCK"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["BELLSPROUT"],
        MON_ID["KRABBY"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["JYNX"],
        MON_ID["JYNX"],
        MON_ID["JYNX"],
    ],
    0x114cd: [ # VermilionStreetsWildMons
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["SPEAROW"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["MEOWTH"],
        MON_ID["MEOWTH"],
        MON_ID["BELLSPROUT"],
        MON_ID["BELLSPROUT"],
        MON_ID["SHELLDER"],
        MON_ID["SHELLDER"],
        MON_ID["DROWZEE"],
        MON_ID["DROWZEE"],
        MON_ID["SPEAROW"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
    ],
    0x114dd: [ # VermilionStreetsWildMonsRare
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["MEOWTH"],
        MON_ID["BELLSPROUT"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["FARFETCH_D"],
        MON_ID["SHELLDER"],
        MON_ID["SHELLDER"],
        MON_ID["DROWZEE"],
        MON_ID["DROWZEE"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
    ],
    0x114ed: [ # RockMountainWildMons
        MON_ID["RATTATA"],
        MON_ID["SPEAROW"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["ZUBAT"],
        MON_ID["DIGLETT"],
        MON_ID["DIGLETT"],
        MON_ID["MACHOP"],
        MON_ID["SLOWPOKE"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["SLOWPOKE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["VOLTORB"],
        MON_ID["VOLTORB"],
    ],
    0x114fd: [ # RockMountainWildMonsRare
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["DIGLETT"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["SLOWPOKE"],
        MON_ID["SLOWPOKE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["VOLTORB"],
        MON_ID["VOLTORB"],
        MON_ID["MR_MIME"],
        MON_ID["MR_MIME"],
        MON_ID["MR_MIME"],
    ],
    0x1150d: [ # CeladonCityWildMons
        MON_ID["PIDGEY"],
        MON_ID["PIDGEY"],
        MON_ID["VULPIX"],
        MON_ID["VULPIX"],
        MON_ID["ODDISH"],
        MON_ID["ODDISH"],
        MON_ID["MEOWTH"],
        MON_ID["MEOWTH"],
        MON_ID["PORYGON"],
        MON_ID["EEVEE"],
        MON_ID["MANKEY"],
        MON_ID["MANKEY"],
        MON_ID["GROWLITHE"],
        MON_ID["GROWLITHE"],
        MON_ID["BELLSPROUT"],
        MON_ID["BELLSPROUT"],
    ],
    0x1151d: [ # CeladonCityWildMonsRare
        MON_ID["CLEFAIRY"],
        MON_ID["CLEFAIRY"],
        MON_ID["ABRA"],
        MON_ID["ABRA"],
        MON_ID["SCYTHER"],
        MON_ID["PINSIR"],
        MON_ID["EEVEE"],
        MON_ID["EEVEE"],
        MON_ID["EEVEE"],
        MON_ID["PORYGON"],
        MON_ID["PORYGON"],
        MON_ID["PORYGON"],
        MON_ID["PORYGON"],
        MON_ID["DRATINI"],
        MON_ID["DRATINI"],
        MON_ID["DRATINI"],
    ],
    0x1152d: [ # FuchsiaCityWildMons
        MON_ID["VENONAT"],
        MON_ID["VENONAT"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["KRABBY"],
        MON_ID["EXEGGCUTE"],
        MON_ID["EXEGGCUTE"],
        MON_ID["KANGASKHAN"],
        MON_ID["KANGASKHAN"],
        MON_ID["EXEGGCUTE"],
        MON_ID["GOLDEEN"],
        MON_ID["GOLDEEN"],
        MON_ID["KANGASKHAN"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
    ],
    0x1153d: [ # FuchsiaCityWildMonsRare
        MON_ID["VENONAT"],
        MON_ID["VENONAT"],
        MON_ID["VENONAT"],
        MON_ID["VENONAT"],
        MON_ID["KRABBY"],
        MON_ID["EXEGGCUTE"],
        MON_ID["EXEGGCUTE"],
        MON_ID["EXEGGCUTE"],
        MON_ID["EXEGGCUTE"],
        MON_ID["KANGASKHAN"],
        MON_ID["KANGASKHAN"],
        MON_ID["KANGASKHAN"],
        MON_ID["KANGASKHAN"],
        MON_ID["GOLDEEN"],
        MON_ID["MAGIKARP"],
        MON_ID["MAGIKARP"],
    ],
    0x1154d: [ # SafariZoneWildMons
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_F"],
        MON_ID["CHANSEY"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["DRATINI"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["DODUO"],
        MON_ID["TAUROS"],
        MON_ID["PINSIR"],
        MON_ID["RHYHORN"],
        MON_ID["RHYHORN"],
        MON_ID["RHYHORN"],
    ],
    0x1155d: [ # SafariZoneWildMonsRare
        MON_ID["NIDORAN_F"],
        MON_ID["NIDORAN_F"],
        MON_ID["PARAS"],
        MON_ID["PARAS"],
        MON_ID["RHYHORN"],
        MON_ID["RHYHORN"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["CHANSEY"],
        MON_ID["PINSIR"],
        MON_ID["PINSIR"],
        MON_ID["TAUROS"],
        MON_ID["TAUROS"],
        MON_ID["DRATINI"],
        MON_ID["DRATINI"],
    ],
    0x1156d: [ # SaffronCityWildMons
        MON_ID["PIDGEY"],
        MON_ID["LAPRAS"],
        MON_ID["EKANS"],
        MON_ID["EKANS"],
        MON_ID["HITMONLEE"],
        MON_ID["SANDSHREW"],
        MON_ID["SANDSHREW"],
        MON_ID["HITMONCHAN"],
        MON_ID["VULPIX"],
        MON_ID["ODDISH"],
        MON_ID["ODDISH"],
        MON_ID["MEOWTH"],
        MON_ID["MANKEY"],
        MON_ID["GROWLITHE"],
        MON_ID["BELLSPROUT"],
        MON_ID["BELLSPROUT"],
    ],
    0x1157d: [ # SaffronCityWildMonsRare
        MON_ID["PIDGEY"],
        MON_ID["EKANS"],
        MON_ID["SANDSHREW"],
        MON_ID["VULPIX"],
        MON_ID["MEOWTH"],
        MON_ID["MANKEY"],
        MON_ID["GROWLITHE"],
        MON_ID["HITMONLEE"],
        MON_ID["HITMONLEE"],
        MON_ID["HITMONLEE"],
        MON_ID["HITMONCHAN"],
        MON_ID["HITMONCHAN"],
        MON_ID["HITMONCHAN"],
        MON_ID["LAPRAS"],
        MON_ID["LAPRAS"],
        MON_ID["LAPRAS"],
    ],
    0x1158d: [ # CinnabarIslandWildMons
        MON_ID["VULPIX"],
        MON_ID["VULPIX"],
        MON_ID["VULPIX"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["MAGMAR"],
        MON_ID["AERODACTYL"],
        MON_ID["GRIMER"],
        MON_ID["GRIMER"],
        MON_ID["GRIMER"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
    ],
    0x1159d: [ # CinnabarIslandWildMonsRare
        MON_ID["VULPIX"],
        MON_ID["PONYTA"],
        MON_ID["PONYTA"],
        MON_ID["GRIMER"],
        MON_ID["GRIMER"],
        MON_ID["KOFFING"],
        MON_ID["KOFFING"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
        MON_ID["TANGELA"],
        MON_ID["MAGMAR"],
        MON_ID["MAGMAR"],
        MON_ID["MAGMAR"],
        MON_ID["AERODACTYL"],
        MON_ID["AERODACTYL"],
        MON_ID["AERODACTYL"],
    ],
    0x115ad: [ # IndigoPlateauWildMons
        MON_ID["SPEAROW"],
        MON_ID["SANDSHREW"],
        MON_ID["ZUBAT"],
        MON_ID["ZUBAT"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["GEODUDE"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["ONIX"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
    ],
    0x115bd: [ # IndigoPlateauWildMonsRare
        MON_ID["SPEAROW"],
        MON_ID["SANDSHREW"],
        MON_ID["ZUBAT"],
        MON_ID["MACHOP"],
        MON_ID["GEODUDE"],
        MON_ID["ONIX"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["DITTO"],
        MON_ID["MOLTRES"],
        MON_ID["MOLTRES"],
        MON_ID["MOLTRES"],
        MON_ID["MEWTWO"],
        MON_ID["MEWTWO"],
        MON_ID["MEWTWO"],
        MON_ID["MEW"],
    ],
}
EVO_COORDS = bytes([
    0x00, 0x11, 0x00, 0x23,#  Red Field
    0x00, 0x2E, 0x00, 0x77, # Blue Field
])

RECIEVE_TABLE = bytes([
    # Routine
    0x7A,0xF5,  # 00 Pika Fallback, shouldn't be called
    0x40,0x3F,  # 01 Catchem Mode
    0x7A,0xF5,  # 02 Small Reward (Used to clear port)
    0x6F,0x83,  # 03 Pika Power
    0x70,0xC1,  # 04 Bonus Multiplier
    0x6F,0xF3,  # 05 Big Points
    0x6F,0x69,  # 06 Ball Saver
    0x6F,0xA7,  # 07 extra Ball
    0x70,0x40,  # 08 Ball Upgrade
    0x7D,0x00,  # 09 Evolution Mode
    0x00,0x00,  # 0A 
    0x00,0x00,  # 0B 
    0x00,0x00,  # 0C 
    0x00,0x00,  # 0D 
    0x00,0x00,  # 0E 
    0x7A,0xF5,  # 0F 

    # ROM Bank
    0x03,  # Fallback
    0x04,  # 01 Catchem
    0x03,  # 02
    0x03,  # 03 Pika Power
    0x03,  # 04 Bonus Multiplier
    0x03,  # 05 Big Points
    0x03,  # 06 Ball Saver
    0x03,  # 07 extra Ball
    0x03,  # 08 Ball Upgrade
    0x03,  # 09 Evolution Mode
    0x03,  # 0A
    0x03,  # 0B
    0x03,  # 0C
    0x03,  # 0D
    0x03,  # 0E
    0x03,  # 0F
])

slot_rewards = {
    0xF439: 0x07,
    0xF44D: 0x08,
    0xF44D: 0x07,
    0xF457: 0x07,
    0xF463: 0x07,
    0xF46B: 0x08,
    0xF475: 0x08,
    0xF47F: 0x07,
    0xF489: 0x07,
    0xF499: 0x08,
    0xF49D: 0x07,
    0xF4A7: 0x08,
    0xF4B1: 0x07,
    0xF4BB: 0x07,
    0xF4C7: 0x08,
    0xF4CF: 0x07,
    0xF4D9: 0x08,
    0xF4E3: 0x07,
    0xF4ED: 0x07,
    0xF4FD: 0x08,
    0xF501: 0x07,
    0xF50B: 0x08,
    0xF515: 0x07,
    0xF51F: 0x07,
    0xF52B: 0x08,
}
required_mon_data = [
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03,
        0x03,0x03,0x03,0x03,0x03,0x03,0x03,0x03
    ]