location_ids = {
    "Lost Village: Above Entrance": 0x01,
    "Lost Village: Upper Big Room Corner": 0x02,
    "Lost Village: Pre-Boss Room Upper": 0x03,
    "Lost Village: Pre-Boss Room Lower": 0x04,
    "Lost Village: Drawbridge Room": 0x05,
    "Lost Village: Above Drawbridge": 0x06,
    "Lost Village: In Moat": 0x07,
    "Flying Armor Soul": 0x08,
    "Lost Village: Flying Armor Indoor Room": 0x09,
    "Lost Village: West Plaza": 0x0A,
    "Lost Village: West Building Upper": 0x0B,
    "Lost Village: West Building Lower": 0x0C,
    "Lost Village: Central Building": 0x0D,
    "Lost Village: East Plaza": 0x0E,
    "Lost Village: Hidden Floor Room 1": 0x0F,
    "Lost Village: Hidden Floor Room 2": 0x10,
    "Lost Village: Mirror Room Left": 0x11,
    "Lost Village: Mirror Room Right": 0x12,
    "Lost Village: Axe Armor Hallway": 0x13,
    "Lost Village: Underground Shaft": 0x14,
    "Lost Village: Above Guest House Entrance": 0x15,

    "Wizardry Lab: Mirror Room": 0x16,
    "Wizardry Lab: Mirror World": 0x17,
    "Wizardry Lab: Main Entry Shaft": 0x18,
    "Wizardry Lab: Upper Big Room": 0x19,
    "Wizardry Lab: West Gate": 0x1A,
    "Wizardry Lab: Behind West Gate": 0x1B,
    "Wizardry Lab: Ceiling Secret Room": 0x1C,
    "Balore Soul": 0x1D,
    "Wizardry Lab: East Gate": 0x1E,
    "Wizardry Lab: Money Gate": 0x1F,
    "Wizardry Lab: Underwater Left": 0x20,
    "Wizardry Lab: Underwater Right": 0x21,
    "Wizardry Lab: Above Water": 0x22,

    "Garden of Madness: Lower Tree Hallway": 0x23,
    "Garden of Madness: West Big Room": 0x24,
    "Garden of Madness: West Big Room Alcove": 0x25,
    "Garden of Madness: West Upper Room": 0x26,
    "Garden of Madness: Hidden Room": 0x27,
    "Garden of Madness: Center Room": 0x28,
    "Garden of Madness: Money Gate": 0x29,
    "Garden of Madness: Underground Room": 0x2A,
    "Garden of Madness: East Alcove": 0x2B,

    "Demon Guest House: Secret Room": 0x2C,
    "Demon Guest House: Antechamber": 0x2D,
    "Demon Guest House: Lower Main Chamber Bottom Room": 0x2E,
    "Demon Guest House: Puppet Hole": 0x2F,
    "Demon Guest House: Number 1 Room": 0x30,
    "Demon Guest House: Number 5 Room": 0x31,
    "Demon Guest House: Number 8 Room": 0x32,
    "Demon Guest House: Number 9 Room": 0x33,
    "Demon Guest House: Number 12 Room": 0x34,
    "Demon Guest House: Mirror World": 0x35,
    "Demon Guest House: Mirror Room": 0x36,
    "Demon Guest House: Doll Alcove": 0x37,
    "Demon Guest House: West Wing Left": 0x38,
    "Demon Guest House: West Wing Right": 0x39,
    "Puppet Master Soul": 0x3A,
    "Demon Guest House: Ice Block Room Left": 0x3B,
    "Demon Guest House: Ice Block Room Right": 0x3C,
    "Demon Guest House: Central Main Chamber Bottom Room": 0x3D,
    "Demon Guest House: Central Main Chamber Middle Room": 0x3E,
    "Demon Guest House: Central Main Chamber Top Room": 0x3F,
    "Paranoia Soul": 0x40,
    "Demon Guest House: Beyond Paranoia": 0x41,
    "Demon Guest House: Paranoia Mirror": 0x42,

    "Dark Chapel: Entrance Alcove": 0x43,
    "Dark Chapel: Catacombs Top Left": 0x44,
    "Dark Chapel: Catacombs Middle Room": 0x45,
    "Dark Chapel: Catacombs Soul Barrier": 0x46,
    "Dark Chapel: Catacombs Mirror Room": 0x47,
    "Dark Chapel: Catacombs Mirror World": 0x48,
    "Dark Chapel: Big Square Room Alcove": 0x49,
    "Dark Chapel: Main Room": 0x4A,
    "Dark Chapel: Bell Room In Bell": 0x4B,
    "Dark Chapel: Bell Room Top Left": 0x4C,
    "Dark Chapel: Bell Room Right": 0x4D,
    "Dark Chapel: Post-Dimitrii Room": 0x60,
    "Malphas Soul": 0x61,
    "Dark Chapel: Big Room Top Right": 0x4E,
    "Dark Chapel: Big Room Central": 0x4F,
    "Dark Chapel: Big Room Lower": 0x50,

    "Condemned Tower: 1F West": 0x51,
    "Condemned Tower: 1F East": 0x52,
    "Condemned Tower: 2F East": 0x53,
    "Condemned Tower: 5F West": 0x54,
    "Condemned Tower: 7F West": 0x55,
    "Condemned Tower: Top of the Tower": 0x56,
    "Gergoth Soul": 0x57,

    "Cursed Clock Tower: Money Gate": 0x58,
    "Cursed Clock Tower: Lower Corner Room": 0x59,
    "Cursed Clock Tower: Mirror Room": 0x5A,
    "Cursed Clock Tower: Mirror World": 0x5B,
    "Cursed Clock Tower: Bugbear Hallway": 0x5C,
    "Cursed Clock Tower: East Gear Room": 0x5D,
    "Cursed Clock Tower: Spike Room Secret": 0x5E,
    "Zephyr Soul": 0x5F,

    "Rahab Soul": 0x62,
    "Subterranean Hell: Giant Underwater Room Center Left": 0x63,
    "Subterranean Hell: Giant Underwater Room Center Right": 0x64,
    "Subterranean Hell: Giant Underwater Room Top Left": 0x65,
    "Subterranean Hell: Giant Underwater Room Bottom Right": 0x66,
    "Subterranean Hell: Near Save Room": 0x67,
    "Subterranean Hell: Central Lower Room": 0x68,
    "Subterranean Hell: Central Upper Room": 0x69,
    "Subterranean Hell: Behind Waterfall": 0x6A,
    "Subterranean Hell: Waterfall Room Lower": 0x6B,
    "Subterranean Hell: Waterfall Room Middle": 0x6C,
    "Subterranean Hell: Waterfall Room Upper": 0x6D,

    "Silenced Ruins: Ice Block Room": 0x6E,
    "Bat Company Soul": 0x6F,
    "Silenced Ruins: Mirror Room": 0x70,
    "Silenced Ruins: Mirror World": 0x71,
    
    "The Pinnacle: Lower Hidden Room": 0x72,
    "The Pinnacle: Under Big Staircase": 0x73,
    "The Pinnacle: Central Indoor Room": 0x74,
    "The Pinnacle: Central Outdoor Room": 0x75,
    "The Pinnacle: Before Throne Room Secret Left": 0x76,
    "The Pinnacle: Before Throne Room Secret Right": 0x77,
    "The Pinnacle: Beyond Throne Room": 0x78,
    "Aguni Soul": 0x79,

    "Death Soul": 0x7A,

    "The Abyss: Sand Area": 0x7B,
    "The Abyss: Ice Area": 0x7C,
    "Abaddon Soul": 0x7D,

    "Imp Soul": 0x7E,
    "Skeleton Soul": 0x7F,
    "Zombie Soul": 0x80,
    "Axe Armor Soul": 0x81,
    "Student Witch Soul": 0x82,
    "Warg Soul": 0x83,
    "Bomber Armor Soul": 0x84,
    "Amalaric Sniper Soul": 0x85,
    "Cave Troll Soul": 0x86,
    "Waiter Skeleton Soul": 0x87,
    "Slime Soul": 0x88,
    "Yorick Soul": 0x89,
    "Une Soul": 0x8A,
    "Mandragora Soul": 0x8B,
    "Rycuda Soul": 0x8C,
    "Fleaman Soul": 0x8D,
    "Ripper Soul": 0x8E,
    "Guillotiner Soul": 0x8F,
    "Killer Clown Soul": 0x90,
    "Malachi Soul": 0x91,
    "Disc Armor Soul": 0x92,
    "Great Axe Armor Soul": 0x93,
    "Slaughterer Soul": 0x94,
    "Hell Boar Soul": 0x95,
    "Frozen Shade Soul": 0x96,
    "Merman Soul": 0x97,
    "Larva Soul": 0x98,
    "Ukoback Soul": 0x99,
    "Decarabia Soul": 0x9A,
    "Succubus Soul": 0x9B,
    "Slogra Soul": 0x9C,
    "Erinys Soul": 0x9D,
    "Homunculus Soul": 0x9E,
    "Witch Soul": 0x9F,
    "Fish Head Soul": 0xA0,
    "Mollusca Soul": 0xA1,
    "Dead Mate Soul": 0xA2,
    "Killer Fish Soul": 0xA3,
    "Malacoda Soul": 0xA4,
    "Flame Demon Soul": 0xA5,
    "Black Panther Soul": 0xA6,
    "Armor Knight Soul": 0xA7,
    "Spin Devil Soul": 0xA8,
    "Skull Archer Soul": 0xA9,
    "Ghost Soul": 0xAA,
    "Yeti Soul": 0xAB,
    "Buer Soul": 0xAC,
    "Manticore Soul": 0xAD,
    "Mushussu Soul": 0xAE,
    "White Dragon Soul": 0xAF,
    "Catoblepas Soul": 0xB0,
    "Gorgon Soul": 0xB1,
    "Persephone Soul": 0xB2,
    "Flying Humanoid Soul": 0xB3,
    "Devil Soul": 0xB4,
    "Medusa Head Soul": 0xB5,
    "Final Guard Soul": 0xB6,
    "Werewolf Soul": 0xB7,
    "Alura Une Soul": 0xB8,
    "Iron Golem Soul": 0xB9,
    "Bone Ark Soul": 0xBA,
    "Barbariccia Soul": 0xBB,
    "Valkyrie Soul": 0xBC,
    "Bat Soul": 0xBD,
    "Great Armor Soul": 0xBE,
    "Mini Devil Soul": 0xBF,
    "Harpy Soul": 0xC0,
    "Corpseweed Soul": 0xC1,
    "Quetzalcoatl Soul": 0xC2,
    "Needles Soul": 0xC3,
    "Alastor Soul": 0xC4,
    "Gaibon Soul": 0xC5,
    "Golem Soul": 0xC6,
    "Bone Pillar Soul": 0xC7,
    "Lilith Soul": 0xC8,
    "Ghost Dancer Soul": 0xC9,
    "Tanjelly Soul": 0xCA,
    "Bugbear Soul": 0xCB,
    "Arc Demon Soul": 0xCC,
    "Giant Slug Soul": 0xCD,
    "Killer Doll Soul": 0xCE,
    "Tombstone Soul": 0xCF,
    "Treant Soul": 0xD0,
    "Ghoul Soul": 0xD1,
    "Skelerang Soul": 0xD2,
    "Skeleton Ape Soul": 0xD3,
    "Dead Warrior Soul": 0xD4,
    "Dead Pirate Soul": 0xD5,
    "Draghignazzo Soul": 0xD6,
    "Heart Eater Soul": 0xD7,
    "Peeping Eye Soul": 0xD8,
    "Skeleton Farmer Soul": 0xD9,
    "The Creature Soul": 0xDA,
    "Mimic Soul": 0xDB,
    "Mothman Soul": 0xDC,
    "Ouija Table Soul": 0xDD,
    "Dead Crusader Soul": 0xDE,
    "Stolas Soul": 0xDF,
    "Wakwak Tree Soul": 0xE0,
    "Procel Soul": 0xE1,
    "Mud Demon Soul": 0xE2,
    "Wizardry Lab: West Gate Button": 0xE3,
    "Wizardry Lab: East Gate Button": 0xE4,
    "Garden of Madness: Gate Button": 0xE5,
    "Subterranean Hell: Gate Button": 0xE6
}