from typing import Dict, NamedTuple, Set

class WOLLocationData(NamedTuple):
    region: str
    location_group: str
    categories: Set[str] = {}
    is_dlc: bool = False

base_id = 752813602

location_table: Dict[str, WOLLocationData] = {
    "Your Family's Farm - Your Bookcase": WOLLocationData("Your Family's Farm", "Your Family's Farm"),
    "Your Family's Farm - Souvenir Shelf (Item 1)": WOLLocationData("Your Family's Farm", "Your Family's Farm", is_dlc=True),
    "Your Family's Farm - Souvenir Shelf (Item 2)": WOLLocationData("Your Family's Farm", "Your Family's Farm", is_dlc=True),
    "Your Family's Farm - Rufus' Toybox": WOLLocationData("Your Family's Farm", "Your Family's Farm"),
    "Your Family's Farm - Father's Gift": WOLLocationData("Your Family's Farm", "Your Family's Farm"),
    "Your Family's Farm - Mother's Gift": WOLLocationData("Your Family's Farm", "Your Family's Farm"),
    "Dirtwater - Spittoon": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater - Flower Girl": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Guest Room - Table": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Saloon - Bartender's Mini Piano": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Saloon - Chef's Mail Key": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Saloon - Chef's Quest Complete": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Post Office - Postal Codes": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Post Office - P.O. Box 114": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Post Office - P.O. Box 441": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Mercantile - Item 1": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater Mercantile - Item 2": WOLLocationData("Dirtwater", "Dirtwater"),
    "Dirtwater (Tony's Boots) - Item 1": WOLLocationData("Tony's Boots", "Tony's Boots"),
    "Dirtwater (Tony's Boots) - Item 2": WOLLocationData("Tony's Boots", "Tony's Boots"),
    "Dirtwater (Tony's Boots) - Item 3": WOLLocationData("Tony's Boots", "Tony's Boots"),
    "Dirtwater (Tony's Boots) - Bonus Item": WOLLocationData("Tony's Boots", "Tony's Boots"),
    "Dirtwater (Murray's Curiosity & Bean) - Item 1": WOLLocationData("Murray's Curiosity & Bean", "Murray's Curiosity & Bean"),
    "Dirtwater (Murray's Curiosity & Bean) - Item 2": WOLLocationData("Murray's Curiosity & Bean", "Murray's Curiosity & Bean"),
    "Dirtwater (Murray's Curiosity & Bean) - Item 3": WOLLocationData("Murray's Curiosity & Bean", "Murray's Curiosity & Bean"),
    "Dirtwater (Murray's Curiosity & Bean) - Item 4": WOLLocationData("Murray's Curiosity & Bean", "Murray's Curiosity & Bean"),
    "Dirtwater (Murray's Curiosity & Bean) - Bonus Item": WOLLocationData("Murray's Curiosity & Bean", "Murray's Curiosity & Bean"),
    "Dirtwater (Grady's Fine Leather Goods) - Item 1": WOLLocationData("Grady's Fine Leather Goods", "Grady's Fine Leather Goods"),
    "Dirtwater (Grady's Fine Leather Goods) - Item 2": WOLLocationData("Grady's Fine Leather Goods", "Grady's Fine Leather Goods"),
    "Dirtwater (Grady's Fine Leather Goods) - Item 3": WOLLocationData("Grady's Fine Leather Goods", "Grady's Fine Leather Goods"),
    "Dirtwater (Grady's Fine Leather Goods) - Bonus Item": WOLLocationData("Grady's Fine Leather Goods", "Grady's Fine Leather Goods"),
    "Dirtwater (Alexandria's Bookstore) - Item 1": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 2": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 3": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 4": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 5": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 6": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Item 7": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Dirtwater (Alexandria's Bookstore) - Bonus Item": WOLLocationData("Alexandria's Bookstore", "Alexandria's Bookstore"),
    "Desert House - Macready's Grave": WOLLocationData("Desert House", "Desert House", is_dlc=True),
    "Desert House - Gang Shakedown": WOLLocationData("Desert House", "Desert House"),
    "Desert House - Gang Killed": WOLLocationData("Desert House", "Desert House"),
    "Shaggy Dog Cave - Bean-Iron Deposit": WOLLocationData("Shaggy Dog Cave", "Shaggy Dog Cave"),
    "Silversmith's House - Spittoon": WOLLocationData("Silversmith's House", "Silversmith's House"),
    "Silversmith's House - Safe": WOLLocationData("Silversmith's House", "Silversmith's House"),
    "Silversmith's House - Shelf (Item 1)": WOLLocationData("Silversmith's House", "Silversmith's House"),
    "Silversmith's House - Shelf (Item 2)": WOLLocationData("Silversmith's House", "Silversmith's House"),
    "Danny's Tannery - Toolbox (Item 1)": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Danny's Tannery - Toolbox (Item 2)": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Danny's Tannery - Center Fight (Item 1)": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Danny's Tannery - Center Fight (Item 2)": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Danny's Tannery - Center Skeleton": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Danny's Tannery (St. Rage Shed) - Grady's Cowsbane Seeds": WOLLocationData("Danny's Tannery", "Danny's Tannery"),
    "Stearns Ranch - Smoking Flower": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch - Outhouse Beast Defeated": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch - Jethro's Bones": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch House - Lockbox": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch House - Pot": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch House - Burnt Bookshelf": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch Cellar - Safe": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Stearns Ranch Cellar - Blood Altar": WOLLocationData("Stearns Ranch", "Stearns Ranch"),
    "Snakepit Mine - Bean-Iron Deposit": WOLLocationData("Snakepit Mine", "Snakepit Mine"),
    "Snakepit Mine - The Pick in the Stone": WOLLocationData("Snakepit Mine", "Snakepit Mine"),
    "The Daveyard - First Grave": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard - Dave J's Grave (Chef Quest)": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard - Far-Right Bone PIle": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard Mausoleum - Rag Pile (Item 1)": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard Mausoleum - Rag Pile (Item 2)": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard Mausoleum - Rag Pile (Item 3)": WOLLocationData("The Daveyard", "The Daveyard"),
    "The Daveyard Mausoleum - The Skeleton of Dave B. Defeated": WOLLocationData("The Daveyard", "The Daveyard"),
    "Buttonwillow's Store - Item 1": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 2": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 3": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 4": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 5": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 6": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Buttonwillow's Store - Item 7": WOLLocationData("Buttonwillow's Store", "Buttonwillow's Store"),
    "Cavern Canyon Spider Cave - Weapens Box": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Cavern Canyon Spider Cave - Medisun Box": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Cavern Canyon Spider Cave - Booze Box": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Cavern Canyon - Stripey Hat Gang Killed": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Cavern Canyon Bar - Bartender's Bones": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Cavern Canyon Bar - Behind the Bar": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    #"Cavern Canyon Kitchen - Doug Rescued": WOLLocationData("Cavern Canyon", "Cavern Canyon"),
    "Fort Cowardice Mess Hall - Table (Item 1)": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Mess Hall - Table (Item 2)": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Mess Hall - Spice Rack (Chef Quest)": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Back Office - General Gob's Hat": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Back Office - General Gob's Pistol": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Back Office - Pie Safe": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice First Tent - Back-Left Footlocker": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice First Tent - Front-Right Footlocker": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice First Tent - Back-Right Footlocker": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Math Tent - Desk Papers": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Math Tent - Shelves": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Math Tent - Safe": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice Goblin Caves - First Victory": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Fort Cowardice - Cannonball": WOLLocationData("Fort Cowardice", "Fort Cowardice"),
    "Gustavson Gulch - Deli Hut": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Storage Hut - Random Item": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Storage Hut - More Random Item": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Storage Hut - Even Randomer Item": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Storage Hut - Randomest Item (Eureka)": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Storage Hut - Secret Item": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch - Theatre Combat": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch - Cafe Hut": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch - Guard Barracks": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Treasure Cave - Bottom Chest (Item 1)": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Treasure Cave - Bottom Chest (Item 2)": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Treasure Cave - Middle Chest": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Gustavson Gulch Destroyed - Dynamite Crate": WOLLocationData("Gustavson Gulch", "Gustavson Gulch"),
    "Railroad Camp (East) - Rock Monster's Remains (Dr. Morton's Quest)": WOLLocationData("Railroad Camp (East)", "Railroad Camp (East)"),
    "The Perfessor's House - Show the Stone Arrow": WOLLocationData("The Perfessor's House", "The Perfessor's House"),
    "Kole Ridge Mine - First Locker (Item 1)": WOLLocationData("Kole Ridge Mine", "Kole Ridge Mine"),
    "Kole Ridge Mine - First Locker (Item 2)": WOLLocationData("Kole Ridge Mine", "Kole Ridge Mine"),
    "Kole Ridge Mine (Level 2) - Triangular Stones": WOLLocationData("Kole Ridge Mine", "Kole Ridge Mine"),
    "Kole Ridge Mine (Level 2) - Bean-Iron Deposit": WOLLocationData("Kole Ridge Mine", "Kole Ridge Mine"),
    "Kole Ridge Mine (Level 3) - Pick-Head": WOLLocationData("Kole Ridge Mine", "Kole Ridge Mine"),
    "Butterfield Ranch - Rope on Fence": WOLLocationData("Butterfield Ranch", "Butterfield Ranch"),
    "Butterfield Ranch - Fireplace": WOLLocationData("Butterfield Ranch", "Butterfield Ranch"),
    "Butterfield Ranch Barn - Milk Shelf": WOLLocationData("Butterfield Ranch", "Butterfield Ranch"),
    "Butterfield Ranch Barn - Toybox": WOLLocationData("Butterfield Ranch", "Butterfield Ranch"),
    "Dynamite Dan's - Item 1": WOLLocationData("Dynamite Dan's", "Dynamite Dan's"),
    "Snake Spring - Temporal Rift": WOLLocationData("Snake Spring", "Snake Spring"),
    "Old Mission Catacombs - First Skull": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Third Skull": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Cemented Skull Pile": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Trash Pile": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Saint Beefus Defeated (Item 1)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Saint Beefus Defeated (Item 2)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Santa Cortada Defeated (Item 1)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Santa Cortada Defeated (Item 2)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Saint Pope Defeated (Item 1)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission Catacombs - Saint Pope Defeated (Item 2)": WOLLocationData("Old Mission", "Old Mission"),
    "Old Mission - Holy Relic Quest Completed": WOLLocationData("Old Mission", "Old Mission"),
    "Destroyed Campsite - Knapsack": WOLLocationData("Destroyed Campsite", "Destroyed Campsite"),
    "Clown Campsite - Clowns Killed (Item 1)": WOLLocationData("Clown Campsite", "Clown Campsite"),
    "Clown Campsite - Clowns Killed (Item 2)": WOLLocationData("Clown Campsite", "Clown Campsite"),
    "Old Millinery - Office Safe": WOLLocationData("Old Millinery", "Old Millinery"),
    "Rescue Mission - Shop Item 1": WOLLocationData("Rescue Mission", "Rescue Mission"),
    "Rescue Mission - Shop Item 2": WOLLocationData("Rescue Mission", "Rescue Mission"),
    "The Silver Plater - Plated the Turnip": WOLLocationData("The Silver Plater", "The Silver Plater"),
    "The Silver Plater - Plated Barbed Wire": WOLLocationData("The Silver Plater", "The Silver Plater"),
    "Lost Dutch Oven Mine - Sluice": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "Lost Dutch Oven Mine (Level 1) - Lockers (Item 1)": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "Lost Dutch Oven Mine (Level 1) - Lockers (Item 2)": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "Lost Dutch Oven Mine (Level 1) - Spittoon": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    #"Lost Dutch Oven Mine (Level 2) - Murray Rescued": WOLLocationData("Lost Dutch Oven Mine"),
    "Lost Dutch Oven Mine (Pit) - Emerald Rock": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "El Vibrato Chamber (Lost Dutch Oven Mine) - Leftmost Box": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "El Vibrato Chamber (Lost Dutch Oven Mine) - Locked Box": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "El Vibrato Ruin - Cylinder": WOLLocationData("Lost Dutch Oven Mine", "Lost Dutch Oven Mine"),
    "Fort Alldead - Trash Can": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead - Mass Grave Item": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead - Knapsack (Item 1)": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead - Knapsack (Item 2)": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead Privy - Bottom-Right Corner": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead Privy - Broken Toilet": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Fort Alldead Barracks - Bottom-Right Footlocker": WOLLocationData("Fort Alldead", "Fort Alldead"),
    "Lazy-A Dude Ranch - Purchased Herbal Remedy": WOLLocationData("Lazy-A Dude Ranch", "Lazy-A Dude Ranch"),
    "Lazy-A Dude Ranch - Dreads Dude Hat Trade": WOLLocationData("Lazy-A Dude Ranch", "Lazy-A Dude Ranch"),
    "Lazy-A Dude Ranch - Cowsbane Harvest": WOLLocationData("Lazy-A Dude Ranch", "Lazy-A Dude Ranch"),
    "Abandoned Pickle Factory Cukes Room - Ghost Put To Rest": WOLLocationData("Abandoned Pickle Factory", "Abandoned Pickle Factory"),
    "Abandoned Pickle Factory Salt Room - Ghost Put To Rest": WOLLocationData("Abandoned Pickle Factory", "Abandoned Pickle Factory"),
    "Abandoned Pickle Factory Vinegar Room - Ghost Put To Rest": WOLLocationData("Abandoned Pickle Factory", "Abandoned Pickle Factory"),
    "Abandoned Pickle Factory Vinegar Room - Coal Cart": WOLLocationData("Abandoned Pickle Factory", "Abandoned Pickle Factory"),
    "Abandoned Pickle Factory - Puzzle Solved": WOLLocationData("Abandoned Pickle Factory", "Abandoned Pickle Factory"),
    "Humming Cave - Grass Outside": WOLLocationData("Humming Cave", "Humming Cave"),
    "Humming Cave - Bean-Iron Deposit": WOLLocationData("Humming Cave", "Humming Cave"),
    "Bizarre Ruin - Half-Buried Pedestal": WOLLocationData("Humming Cave", "Humming Cave"),
    "Circus - Ticket Booth": WOLLocationData("Circus", "Circus"),
    "Circus - Test Your ____ (Ticket Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Might (Large Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Might (Small Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Mind (Large Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Mind (Small Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Aim (Large Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Test Your Aim (Small Prize)": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Balloon Vendor": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus Lost & Found - Item 1": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus Lost & Found - Item 2": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus Lost & Found - Item 3": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus Lost & Found - Item 4": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Stole the Slide Whistle": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Slide Whistle Reward": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus Kid - Lucky Cap Trade": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Survived the Main Act": WOLLocationData("Circus (Inside)", "Circus"),
    "Circus - Barnaby Bob's Safe": WOLLocationData("Circus", "Circus"),
    "Breadwood Mayor's Office - Soup Quest Accepted": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood - Spittoon": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 1": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 2": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 3": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 4": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 5": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 6": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 7": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 8": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 9": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Trading Post - Item 10": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Bunkhouse - Hobart's Camera": WOLLocationData("Breadwood", "Breadwood"),
    "Breadwood Bunkhouse - Footlocker": WOLLocationData("Breadwood", "Breadwood"),
    "Ghostwood Town Hall - Issued Permit": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood - Ghost Cactus": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood - Sharpened Pencil": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Town Hall - Issued ID": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Office Supply - Stapler": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Jail - Stapled Report": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Stable - Got IDDTF": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Salooooon - Staple Remover": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Town Hall - The Final Form": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Town Hall - Permit Finally Processed": WOLLocationData("Ghostwood", "Ghostwood"),
    "Ghostwood Salooooon - Whiskey Bottle": WOLLocationData("Ghostwood", "Ghostwood"),
    "Postal Way Station - Top-Right Newspaper Stack": WOLLocationData("Postal Way Station", "Postal Way Station"),
    "Postal Way Station - Middle Newspaper Stack": WOLLocationData("Postal Way Station", "Postal Way Station"),
    "Chuck's House - Bedroom Dresser": WOLLocationData("Chuck's House", "Chuck's House"),
    "Chuck's House Cellar - Mail Bag": WOLLocationData("Chuck's House Cellar", "Chuck's House"),
    "Chuck's House Cellar - Bookcase (Item 1)": WOLLocationData("Chuck's House Cellar", "Chuck's House"),
    "Chuck's House Cellar - Bookcase (Item 2)": WOLLocationData("Chuck's House Cellar", "Chuck's House"),
    "Chuck's House Cellar - Bookcase (Item 3)": WOLLocationData("Chuck's House Cellar", "Chuck's House"),
    "Chuck's House Cellar - Nightstand": WOLLocationData("Chuck's House Cellar", "Chuck's House"),
    "Soupstock Lode (Level 1) - Workbench Toolbox (Item 1)": WOLLocationData("Soupstock Lode", "Soupstock Lode"),
    "Soupstock Lode (Level 1) - Workbench Toolbox (Item 2)": WOLLocationData("Soupstock Lode", "Soupstock Lode"),
    "Soupstock Lode (Level 1) - Bean-Iron Deposit (Bottom Left)": WOLLocationData("Soupstock Lode", "Soupstock Lode"),
    "Soupstock Lode (Elevator Room) - Knapsack": WOLLocationData("Soupstock Lode", "Soupstock Lode"),
    "El Vibrato Chamber (Soupstock Lode) - Chest": WOLLocationData("Soupstock Lode", "Soupstock Lode"),
    "Ol' Schmaltz Brewery - Dead Guy": WOLLocationData("Ol' Schmaltz Brewery", "Ol' Schmaltz Brewery"),
    "Ol' Schmaltz Brewery - Deceased Yeast Beast": WOLLocationData("Ol' Schmaltz Brewery", "Ol' Schmaltz Brewery"),
    "Ol' Schmaltz Brewery - Shelf": WOLLocationData("Ol' Schmaltz Brewery", "Ol' Schmaltz Brewery"),
    "Baker Boys' Hideout - Bread Recovered": WOLLocationData("Baker Boys' Hideout", "Baker Boys' Hideout"),
    "Military Cemetery - Shovel By Coffins": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - Shed Tools": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - Plot 13": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - Plot 420": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - Plot 666": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - Puzzle Plots Solved": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Military Cemetery - 2nd Lt. 69th Innuendo Div. (Combat)": WOLLocationData("Military Cemetery", "Military Cemetery"),
    "Fort Memoriam - Candy Shelf": WOLLocationData("Fort Memoriam", "Fort Memoriam"),
    "Fort Memoriam Barracks - Bookshelf": WOLLocationData("Fort Memoriam", "Fort Memoriam"),
    "Fort Memoriam Barracks - Trash Pile": WOLLocationData("Fort Memoriam", "Fort Memoriam"),
    "Fort Memoriam Barracks - Spittoon": WOLLocationData("Fort Memoriam", "Fort Memoriam"),
    "Fort Memoriam - All Battles Cleared": WOLLocationData("Fort Memoriam", "Fort Memoriam"),
    "Alexandria Ranch - Ruined Bookshelf (Left)": WOLLocationData("Alexandria Ranch", "Alexandria Ranch"),
    "Alexandria Ranch - Smoldering Book Pile": WOLLocationData("Alexandria Ranch", "Alexandria Ranch"),
    "Alexandria Ranch - Ruined Bookshelf (Right)": WOLLocationData("Alexandria Ranch", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Right Bookshelf": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Middle Bookshelf": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Left Bookshelf": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Glass Case (Right)": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Glass Case (Middle)": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    "Alexandria Ranch Vault - Glass Case (Left)": WOLLocationData("Alexandria Ranch Vault", "Alexandria Ranch"),
    #"Alexandria Ranch (Temporal Rift) - Alexandria Rescued": WOLLocationData("Alexandria Ranch"),
    "Curly's Cairn - Under the Cairn": WOLLocationData("Alexandria Ranch", "Alexandria Ranch"),
    "Roy Bean's House - Spittoon": WOLLocationData("Roy Bean's House", "Roy Bean's House"),
    "Roy Bean's House - Honey Bean": WOLLocationData("Roy Bean's House", "Roy Bean's House"),
    "Jelly Bean Thieves' Hideout - Thieves Killed (Revolver)": WOLLocationData("Jelly Bean Thieves' Hideout", "Jelly Bean Thieves' Hideout"),
    "Jelly Bean Thieves' Hideout - Thieves Killed (Hat)": WOLLocationData("Jelly Bean Thieves' Hideout", "Jelly Bean Thieves' Hideout"),
    "Jelly Bean Thieves' Hideout - Crate Beside Stove": WOLLocationData("Jelly Bean Thieves' Hideout", "Jelly Bean Thieves' Hideout"),
    "Jelly Bean Thieves' Hideout - Crate Beside Bed": WOLLocationData("Jelly Bean Thieves' Hideout", "Jelly Bean Thieves' Hideout"),
    "Jelly Bean Thieves' Hideout - Jellybean Jar": WOLLocationData("Jelly Bean Thieves' Hideout", "Jelly Bean Thieves' Hideout"),
    "Ol' Granddad (Floor 4) - Jellybean Jar": WOLLocationData("Ol' Granddad", "Ol' Granddad"),
    "Shroomcave - First Magic Mushroom": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave - Second Magic Mushroom": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave - Third Magic Mushroom": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave - Dirty Knapsack": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave - Sleeping Cultist (Item 1)": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave - Sleeping Cultist (Item 2)": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave (Hidden Lounge) - Lava Lamp": WOLLocationData("Shroomcave", "Shroomcave"),
    "Shroomcave (Hidden Lounge) - Jellybean Jar": WOLLocationData("Shroomcave", "Shroomcave"),
    #"Fort of Darkness (First Tent) - Convinced Tony": WOLLocationData("Fort of Darkness"),
    "Fort of Darkness (First Tent) - Irene's Pliers": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (First Tent) - Free Mushroom": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Second Tent) - Animal Skeleton": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Second Tent) - Bone Trader (Chips)": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Second Tent) - Bone Trader (Bones)": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Second Tent) - Bone Trader (10 Gold Teeth)": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Second Tent) - Bone Trader (23 Gold Teeth)": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Fifth Tent) - Gun Safe": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness (Fifth Tent) - Bookcase": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort of Darkness - Temporal Rift": WOLLocationData("Fort of Darkness", "Fort of Darkness"),
    "Fort Treason Barracks - Top-Left Footlocker": WOLLocationData("Fort Treason", "Fort Treason"),
    "Fort Treason Barracks - Top-Right Footlocker (Item 1)": WOLLocationData("Fort Treason", "Fort Treason"),
    "Fort Treason Barracks - Top-Right Footlocker (Item 2)": WOLLocationData("Fort Treason", "Fort Treason"),
    "Fort Treason Barracks - Bottom-Right Footlocker": WOLLocationData("Fort Treason", "Fort Treason"),
    "Jumbleneck Mine - Rock Pile By Elevator": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine - Grease Barrel": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine Foreman's Office - Hatrack": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine Foreman's Office - Desk": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine Foreman's Office - Safe (Item 1)": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine Foreman's Office - Safe (Item 2)": WOLLocationData("Jumbleneck Mine", "Jumbleneck Mine"),
    "Jumbleneck Mine (Inside) - The Pick in the Stone": WOLLocationData("Jumbleneck Mine (Inside)", "Jumbleneck Mine"),
    "Jumbleneck Mine (Left Tunnel) - Lunchbox": WOLLocationData("Jumbleneck Mine (Inside)", "Jumbleneck Mine"),
    "Jumbleneck Mine (Left Tunnel) - Bean-Iron Deposit": WOLLocationData("Jumbleneck Mine (Inside)", "Jumbleneck Mine"),
    "Jumbleneck Mine (Left Tunnel) - Dynamite Crate": WOLLocationData("Jumbleneck Mine (Inside)", "Jumbleneck Mine"),
    "Jumbleneck Mine (Right Tunnel) - Idol": WOLLocationData("Jumbleneck Mine (Inside)", "Jumbleneck Mine"),
    "El Vibrato Construction Facility - BUGAANZEVE": WOLLocationData("Curious Copse", "Curious Copse"),
    "El Vibrato Construction Facility - HOSOM NOAN NOFU": WOLLocationData("Curious Copse", "Curious Copse"),
    "Curious Abandoned Well Facility (Equipment Fabrication) - Item 1": WOLLocationData("Curious Abandoned Well Facility", "Curious Abandoned Well"),
    "Curious Abandoned Well Facility (Equipment Fabrication) - Item 2": WOLLocationData("Curious Abandoned Well Facility", "Curious Abandoned Well"),
    "Curious Abandoned Well Facility (Secondary Storage) - Top Chest": WOLLocationData("Curious Abandoned Well Facility", "Curious Abandoned Well"),
    "Curious Abandoned Well Facility (Secondary Storage) - Bottom Chest": WOLLocationData("Curious Abandoned Well Facility", "Curious Abandoned Well"),
    "Curious Abandoned Well Facility (Secondary Storage) - Weird Device": WOLLocationData("Curious Abandoned Well Facility", "Curious Abandoned Well"),
    "Reboot Hill (Plot 1) - Granddaughter Puzzle": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 1) - Wise Ol' Jed Marmot's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 1) - Big Bob Hurlingham's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 1) - Sweet Monument": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Dink 'Scotch' Terkinson's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Fred Deeks' Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Annette Jangle's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Picnic": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Fancy Tomb (Left)": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Fancy Tomb (Middle)": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 2) - Fancy Tomb (Right)": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 3) - Paulette Tootsbury's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 3) - Cultists' Pedestal": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 3) - Outhouse": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 3) - Stanrietta Minkleston's Grave": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "Reboot Hill (Plot 3) - Bernard's Reward": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "ReBoot Hill - Tontine Treasure Chest": WOLLocationData("Reboot Hill", "Reboot Hill"),
    "The West Pole - Petroglyph Puzzle Solved": WOLLocationData("The West Pole", "The West Pole"),
    "The West Pole - Leftmost Cairn (Dr. Morton's Quest)": WOLLocationData("The West Pole", "The West Pole"),
    "Temporal Nexus - Camaro": WOLLocationData("The West Pole", "The West Pole"),
    "Temporal Nexus - Stagecoach": WOLLocationData("The West Pole", "The West Pole"),
    "Temporal Nexus - Robot": WOLLocationData("The West Pole", "The West Pole"),
    "Temporal Nexus - Jawbone": WOLLocationData("The West Pole", "The West Pole"),
    "The Great Garbanzo's Hideout - Between the Cushions": WOLLocationData("The Great Garbanzo's Hideout", "The Great Garbanzo's Hideout"),
    "The Great Garbanzo's Hideout - Under the Pillow": WOLLocationData("The Great Garbanzo's Hideout", "The Great Garbanzo's Hideout"),
    "The Great Garbanzo's Hideout - Bookcase": WOLLocationData("The Great Garbanzo's Hideout", "The Great Garbanzo's Hideout"),
    "The Great Garbanzo's Hideout - Bean-Iron Deposit": WOLLocationData("The Great Garbanzo's Hideout", "The Great Garbanzo's Hideout"),
    #"The Great Garbanzo's Hideout - Arcane Oven": WOLLocationData("The Great Garbanzo's Hideout"),
    "The Old Medicine Show - Bookcase": WOLLocationData("The Old Medicine Show", "The Old Medicine Show"),
    "The Old Medicine Show - Nightstand (Item 1)": WOLLocationData("The Old Medicine Show", "The Old Medicine Show"),
    "The Old Medicine Show - Nightstand (Item 2)": WOLLocationData("The Old Medicine Show", "The Old Medicine Show"),
    "The Old Medicine Show - Nightstand (Item 3)": WOLLocationData("The Old Medicine Show", "The Old Medicine Show"),
    #"The Old Medicine Show - Alchemistry Set": WOLLocationData("The Old Medicine Show"),
    "Hellstrom Ranch (Barn) - Bookshelf": WOLLocationData("Hellstrom Ranch", "Hellstrom Ranch"),
    #"Hellstrom Ranch (Barn) - Leatherworking Bench": WOLLocationData("Hellstrom Ranch"),
    "Petting Cemetery - Accepted Buffalo Quest": WOLLocationData("Petting Cemetery", "Petting Cemetery"),
    "Buffalo Pile (Storage/Assembly) - Robe Next to Slab": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Bathroom) - Magazines": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Bathroom) - Trash Pile": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Sleeping Quarters) - Left Footlocker (Item 1)": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Sleeping Quarters) - Left Footlocker (Item 2)": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Sleeping Quarters) - Right Footlocker": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Buffalo Pile (Sleeping Quarters) - Pedestal": WOLLocationData("Buffalo Pile", "Buffalo Pile"),
    "Madness Maw Mine (Level 2) - Bean-Iron Deposit": WOLLocationData("Madness Maw Mine", "Madness Maw Mine"),
    "Madness Maw Mine (Level 3) - Head Cultist": WOLLocationData("Madness Maw Mine", "Madness Maw Mine"),
    "Madness Maw Mine (Curly's Cave) - Nightstand": WOLLocationData("Madness Maw Mine", "Madness Maw Mine"),
    "Madness Maw Mine (Curly's Cave) - Pie Safe": WOLLocationData("Madness Maw Mine", "Madness Maw Mine"),
    "Madness Maw Mine (Level 4) - Bean-Iron Deposit": WOLLocationData("Madness Maw Mine", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Cylinder": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Cards": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Trash Pile": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Vending Machine (SOMFUKRO)": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Vending Machine (SOMZAKBUNOK)": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Vending Machine (ZEVENOKKRO)": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "El Vibrato Outpost (Madness Maw Mine) - Vending Machine (BUKUZKRO)": WOLLocationData("El Vibrato Outpost (MMM)", "Madness Maw Mine"),
    "Kellogg Ranch (Main Building) - Loose Floorboard": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Office) - Animal Skeleton": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Office) - Desk Drawer": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Top-Left Bed": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Bottom-Middle Bed": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - First Locker (Item 1)": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - First Locker (Item 2)": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Second Locker": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Fourth Locker": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Fifth Locker": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Sixth Locker (Item 1)": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Dormitory) - Sixth Locker (Item 2)": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Kitchen) - Dough Baked": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Barn) - Barbed Wire": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Kellogg Ranch (Barn) - Grain Pile": WOLLocationData("Kellogg Ranch", "Kellogg Ranch"),
    "Necromancer's Tower - Necromancer Defeated": WOLLocationData("Necromancer's Tower", "Necromancer's Tower"),
    "Frisco - Flier on the Street": WOLLocationData("Frisco", "Frisco"),
    "Frisco - Spittoon": WOLLocationData("Frisco", "Frisco"),
    "Fort Unnecessary - Administration Desk": WOLLocationData("Fort Unnecessary", "Fort Unnecessary"),
    "Fort Unnecessary - Time Portal": WOLLocationData("Fort Unnecessary", "Fort Unnecessary"),
    "Abandoned Mine - Drywasher": WOLLocationData("Abandoned Mine", "Abandoned Mine"),
    "Abandoned Mine - Rocks to Right of Entrance": WOLLocationData("Abandoned Mine", "Abandoned Mine"),
    "Abandoned Mine (Inside) - Bean-Iron Deposit": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "Abandoned Mine (Side Tunnel 1) - Bean-Iron Deposit": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "Abandoned Mine (Side Tunnel 2) - Bean-Iron Deposit": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "Abandoned Mine (Side Tunnel 2) - Drilling Machine": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "El Vibrato Storage Room - Card Table (Item 1)": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "El Vibrato Storage Room - Card Table (Item 2)": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "El Vibrato Storage Room - Cylinder": WOLLocationData("Abandoned Mine (Inside)", "Abandoned Mine"),
    "Dr. Morton's House - Workbench": WOLLocationData("Dr. Morton's House", "Dr. Morton's House"),
    "Morton's Quarry (Tiny Diverticulum) - Hex Puzzle": WOLLocationData("Dr. Morton's House", "Dr. Morton's House"),
    "Morton's Quarry - Dr. Morton's Quest Completion": WOLLocationData("Dr. Morton's House", "Dr. Morton's House"),
    "Old Cave - Weird Rock": WOLLocationData("Old Cave", "Old Cave"),
    "Jeweler's Cabin - Coal": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Sapphire": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Cowseye": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Diamond": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Emerald": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Ruby": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Silicon": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Diorite": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "Jeweler's Cabin - Spectacles": WOLLocationData("Jeweler's Cabin", "Jeweler's Cabin"),
    "El Vibrato Chamber (Curious False Mountain) - Chronokey Fabrication": WOLLocationData("Curious False Mountain", "Curious False Mountain"),
    "Alamo Rent-A-Mule - Rented a Mule": WOLLocationData("Alamo Rent-A-Mule", "Alamo Rent-A-Mule"),
    "Curious Flat Plain - Explorer Skeleton": WOLLocationData("Curious Flat Plain", "Curious Flat Plain"),
    "Curious Flat Plain - Garbage Return": WOLLocationData("Curious Flat Plain", "Curious Flat Plain"),
    "Moonshine Still - Free Jar": WOLLocationData("Moonshine Still", "Moonshine Still"),
    "Deepest Delve Mine - Coal Smasher 5000": WOLLocationData("Deepest Delve Mine (Elevator Fixed)", "Deepest Delve Mine"),
    "Deepest Delve Mine (Alt Entrance) - Toolbox": WOLLocationData("Deepest Delve Mine", "Deepest Delve Mine"),
    "Deepest Delve Mine (Alt Entrance) - Bean-Iron Deposit": WOLLocationData("Deepest Delve Mine", "Deepest Delve Mine"),
    "Deepest Delve Mine (Level 2) - Cult Altar": WOLLocationData("Deepest Delve Mine (Elevator Fixed)", "Deepest Delve Mine"),
    "Deepest Delve Mine (Level 2) - Bracelet": WOLLocationData("Deepest Delve Mine (Elevator Fixed)", "Deepest Delve Mine"),
    "El Vibrato Control Center - El Vibrato Quest Completion": WOLLocationData("Deepest Delve Mine (Elevator Fixed)", "Deepest Delve Mine"),
    "Halloway's Hideaway - Shop Item 1": WOLLocationData("Halloway's Hideaway", "Halloway's Hideaway"),
    "Halloway's Hideaway - Shop Item 2": WOLLocationData("Halloway's Hideaway", "Halloway's Hideaway"),
    "Halloway's Hideaway - Half of Curly's Map": WOLLocationData("Halloway's Hideaway", "Halloway's Hideaway"),
    "Halloway's Hideaway - X Marks the Spot": WOLLocationData("Halloway's Hideaway", "Halloway's Hideaway"),
    "Back of Gun Manor - Coal Man Skeleton": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Back of Gun Manor - Compost Heap": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Gun Manor Hedge Maze - Bean Bush": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Gun Manor Hedge Maze - Hedge Wizard Defeated (Item 1)": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Gun Manor Hedge Maze - Hedge Wizard Defeated (Item 2)": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Gun Manor Hedge Maze - Hedge Wizard's Chest": WOLLocationData("Gun Manor Hedge Maze", "Gun Manor Hedge Maze", is_dlc=True),
    "Gun Manor Carriage House - Cabinet (Item 1)": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Carriage House - Cabinet (Item 2)": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Carriage House - Hedge Clippers": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Carriage House - Leftmost Coach": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Carriage House - Middle Coach": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Carriage House - Lathe": WOLLocationData("Gun Manor Carriage House", "Gun Manor Carriage House", is_dlc=True),
    "Gun Manor Visitor Center - Token Smasher (Pistol)": WOLLocationData("Gun Manor Visitor Center", "Gun Manor Visitor Center", is_dlc=True),
    "Gun Manor Visitor Center - Token Smasher (Rifle)": WOLLocationData("Gun Manor Visitor Center", "Gun Manor Visitor Center", is_dlc=True),
    "Gun Manor Visitor Center - Token Smasher (Shotgun)": WOLLocationData("Gun Manor Visitor Center", "Gun Manor Visitor Center", is_dlc=True),
    "Gun Manor Visitor Center - Photo": WOLLocationData("Gun Manor Visitor Center", "Gun Manor Visitor Center", is_dlc=True),
    "Gun Manor Visitor Center - SouvenIRS Stand": WOLLocationData("Gun Manor Visitor Center", "Gun Manor Visitor Center", is_dlc=True),
    "Gun Manor Cellar - Rightmost Cocoon": WOLLocationData("Gun Manor Cellar", "Gun Manor Cellar", is_dlc=True),
    "Gun Manor Cellar - Box of Photos": WOLLocationData("Gun Manor Cellar", "Gun Manor Cellar", is_dlc=True),
    "Gun Manor Cellar - Pie Safe": WOLLocationData("Gun Manor Cellar", "Gun Manor Cellar", is_dlc=True),
    "Gun Manor Laboratory - Science Bench": WOLLocationData("Gun Manor Laboratory", "Gun Manor Laboratory", is_dlc=True),
    "Gun Manor Laboratory - Science Box": WOLLocationData("Gun Manor Laboratory", "Gun Manor Laboratory", is_dlc=True),
    "Gun Manor Laboratory - Workbench": WOLLocationData("Gun Manor Laboratory", "Gun Manor Laboratory", is_dlc=True),
    "Gun Manor Laboratory - Gunsmithing Tools (Worst Gun)": WOLLocationData("Gun Manor Laboratory", "Gun Manor Laboratory", is_dlc=True),
    "Gun Manor Laboratory - Gunsmithing Tools (Opus)": WOLLocationData("Gun Manor Laboratory", "Gun Manor Laboratory", is_dlc=True),
    "Gun Manor Parlor - Tea Cart": WOLLocationData("Gun Manor Parlor", "Gun Manor Parlor", is_dlc=True),
    "Gun Manor Parlor - Sofa Cushions (Murdered Chili)": WOLLocationData("Gun Manor Parlor", "Gun Manor Parlor", is_dlc=True),
    "Gun Manor Kitchen - Spice Rack": WOLLocationData("Gun Manor Kitchen", "Gun Manor Kitchen", is_dlc=True),
    "Gun Manor Kitchen - Cooked the Chili": WOLLocationData("Gun Manor Kitchen", "Gun Manor Kitchen", is_dlc=True),
    "Gun Manor Kitchen - Pot Shelf": WOLLocationData("Gun Manor Kitchen", "Gun Manor Kitchen", is_dlc=True),
    "Gun Manor Larder - Middle Shelf": WOLLocationData("Gun Manor Larder", "Gun Manor Larder", is_dlc=True),
    "Gun Manor Larder - Right Shelf": WOLLocationData("Gun Manor Larder", "Gun Manor Larder", is_dlc=True),
    "Gun Manor Pantry - Back Row Third Rack": WOLLocationData("Gun Manor Pantry", "Gun Manor Pantry", is_dlc=True),
    "Gun Manor Dining Room - Dessert Cart": WOLLocationData("Gun Manor Dining Room", "Gun Manor Dining Room", is_dlc=True),
    "Gun Manor Library - Dictionary (\"Key\")": WOLLocationData("Gun Manor Library", "Gun Manor Library", is_dlc=True),
    "Gun Manor Library - Dictionary (\"Poach\")": WOLLocationData("Gun Manor Library", "Gun Manor Library", is_dlc=True),
    "Gun Manor Library - Fun Law Returned": WOLLocationData("Gun Manor Library", "Gun Manor Library", is_dlc=True),
    "Gun Manor Library - Duelling Banjos Returned": WOLLocationData("Gun Manor Library", "Gun Manor Library", is_dlc=True),
    "Gun Manor Library - Cipher Puzzle Solved": WOLLocationData("Gun Manor Library", "Gun Manor Library", is_dlc=True),
    "Gun Manor Art Gallery - Clock Noon Objection": WOLLocationData("Gun Manor Art Gallery", "Gun Manor Art Gallery", is_dlc=True),
    "Gun Manor Art Gallery - Lawyer Quest Completion": WOLLocationData("Gun Manor Art Gallery", "Gun Manor Art Gallery", is_dlc=True),
    "Gun Manor Restroom - Medicine Cabinet": WOLLocationData("Gun Manor Restroom", "Gun Manor Restroom", is_dlc=True),
    "Gun Manor Restroom - Shower": WOLLocationData("Gun Manor Restroom", "Gun Manor Restroom", is_dlc=True),
    "Gun Manor Guest Room 1 - Bookcase": WOLLocationData("Gun Manor Guest Rooms", "Gun Manor Guest Rooms", is_dlc=True),
    "Gun Manor Guest Room 3 - Sewing Basket": WOLLocationData("Gun Manor Guest Rooms", "Gun Manor Guest Rooms", is_dlc=True),
    "Gun Manor Guest Room 4 - Science Box": WOLLocationData("Gun Manor Guest Rooms", "Gun Manor Guest Rooms", is_dlc=True),
    "Mr. Gun's Manliness Room - Humidor": WOLLocationData("Mr. Gun's Manliness Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Manliness Room - Booze Cart": WOLLocationData("Mr. Gun's Manliness Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Bowling Room - Combat Drop 1": WOLLocationData("Mr. Gun's Bowling Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Bowling Room - Combat Drop 2": WOLLocationData("Mr. Gun's Bowling Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Bowling Room - Combat Drop 3": WOLLocationData("Mr. Gun's Bowling Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Bowling Room - Combat Drop 4": WOLLocationData("Mr. Gun's Bowling Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Mr. Gun's Trophy Room - Moose Head": WOLLocationData("Mr. Gun's Trophy Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Gun Manor Billiards Room - Cue Rack": WOLLocationData("Gun Manor Billiards Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Gun Manor Billiards Room - Pool Table": WOLLocationData("Gun Manor Billiards Room", "Mr. Gun's Manliness Room", is_dlc=True),
    "Gun Manor Music Room - Book Pile": WOLLocationData("Gun Manor Music Room", "Gun Manor Music Room", is_dlc=True),
    "Gun Manor Music Room - Piano": WOLLocationData("Gun Manor Music Room", "Gun Manor Music Room", is_dlc=True),
    "Gun Manor Children's Quarters - Chalkboard": WOLLocationData("Gun Manor Children's Quarters", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Children's Quarters - Dollmine": WOLLocationData("Gun Manor Children's Quarters", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Nursery - Crib": WOLLocationData("Gun Manor Nursery", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Nursery - Teddy Bear Guts": WOLLocationData("Gun Manor Nursery", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Toddler's Room - Toybox": WOLLocationData("Gun Manor Toddler's Room", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Tween Room - Desk": WOLLocationData("Gun Manor Tween Room", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Tween Room - Science Box": WOLLocationData("Gun Manor Tween Room", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Tween Room - Wardrobe": WOLLocationData("Gun Manor Tween Room", "Gun Manor Children's Quarters", is_dlc=True),
    "Gun Manor Tween Room - Under the Bed": WOLLocationData("Gun Manor Tween Room", "Gun Manor Children's Quarters", is_dlc=True),
    "Mrs. Gun's Room - Display Case": WOLLocationData("Mrs. Gun's Room", "Mrs. Gun's Room", is_dlc=True),
    "Mrs. Gun's Room - Peaceful Solution": WOLLocationData("Mrs. Gun's Room", "Mrs. Gun's Room", is_dlc=True),
    "Gun Manor Belfry - Science Box": WOLLocationData("Gun Manor Belfry", "Gun Manor Belfry", is_dlc=True),
    "Wanderin' Sally's Camp - Item 1": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 2": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 3": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 4": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 5": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 6": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 7": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 8": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 9": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 10": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 11": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 12": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 13": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Wanderin' Sally's Camp - Item 14": WOLLocationData("Wanderin' Sally's Camp", "Wanderin' Sally's Camp"),
    "Random Encounter (Any Region) - 7th Encounter": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Any Region) - 13th Encounter": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Any Region) - 21st Encounter": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Murder Pepper (Chef Quest)": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Abandoned Stagecoach": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Corpse of a Cowboy": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Sharpshootin' Bandits": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Moxious Goblin": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region A) - Skeleton of a Beanslinger": WOLLocationData("Random Encounters A", "Random Encounters A"),
    "Random Encounter (Region B) - Quilty-Pantsed Bandit": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Scientifically-Minded Bandit": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Hightailin' Bandit": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Gulch Goblin Cactusjack": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Gulch Goblin Flapjackjack (Spatula)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Gulch Goblin Flapjackjack (Flapjacks)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Gulch Goblin Crackerjack": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Old Viking Skeleton": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Old Wizard Skeleton (Bean Can)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Old Wizard Skeleton (Wizard Hat)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Cattle Baron's Skeleton (Lily)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region B) - Cattle Baron's Skeleton (Top Hat)": WOLLocationData("Random Encounters B", "Random Encounters B"),
    "Random Encounter (Region C) - Grizzled Skinner (Pants)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Grizzled Skinner (Varmint Knife)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Backwoods Butcher (Cleaver)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Backwoods Butcher (Steak)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Clown Hunter": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Jackbooted Gulch Goblin": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Gulch Goblin Juggler": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Gulch Goblin Jeweler (Nail Ring)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Gulch Goblin Jeweler (Glass Ring)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Gulch Goblin Jeweler (Lead Ring)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Gulch Goblin Jeweler (Magic Ring)": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Skeletal Cavalryman": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Deformed Skeleton": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region C) - Skeleton of an Old Hunter": WOLLocationData("Random Encounters C", "Random Encounters C"),
    "Random Encounter (Region D) - 3rd Encounter": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Big Tough Bandit": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Strangely-Helmeted Lunatic": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Breadwood Highwayman": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Goblin Moon Weirdo": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Goblin Chef": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Foul-Mouthed Goblin": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Shot-to-Hell Skeleton": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Electrified Skeleton": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Skeletal Rifleman": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region D) - Drunk Ghost (Give Whiskey)": WOLLocationData("Random Encounters D", "Random Encounters D"),
    "Random Encounter (Region E) - 13th Cowrrupted Encounter": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Vigilante Cultist Hunter": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Wandering Necromancer Cultist (Hood)": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Wandering Necromancer Cultist (Shovel)": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Cow Hunter": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Goblin Wearing a Buffalo Skull": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Goblin Tuna Chef": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Self-Deputized Goblin": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Buffalo Soldier": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Very Smart Skeleton": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region E) - Buffalo Soldier Rifleman": WOLLocationData("Random Encounters E", "Random Encounters E"),
    "Random Encounter (Region F) - Kurtz-Cult Runaway": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Mad Hedge Chef": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Cow-Cult Brigand": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Cactus-Suited Goblin": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Goblin Tanner": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Goblin Grave Robber (Pin)": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Goblin Grave Robber (Field Trauma Kit)": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Thick-Boned Skeleton (Boots)": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Thick-Boned Skeleton (Brochure)": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Mushroom-Covered Skeleton": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region F) - Burnin' Skeleton": WOLLocationData("Random Encounters F", "Random Encounters F"),
    "Random Encounter (Region G) - Insane Construction Worker": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Burning Man": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Bandit Jogger": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Goblin Driftwood Sculptor (Weapon)": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Goblin Driftwood Sculptor (Hat)": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Goblin Driftwood Sculptor (Shield)": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Goblin Clamdigger": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Trigger-Happy Goblin Driftwood Sculptor": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Conquistador's Skeleton": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Seaweed-Draped Skeleton": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region G) - Conquistador Dragoon Skeleton": WOLLocationData("Random Encounters G", "Random Encounters G"),
    "Random Encounter (Region H) - Grizzled Mountain Man": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Back-Country Chef-Magus": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Barista (Coffee)": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Barista (Pants)": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Goblin Miner": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Goblin Gunsmith": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Flashy Goblin": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Bigfoot Skeleton": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Canada-Bound Skeleton": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Skeletal Texas Ranger": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Random Encounter (Region H) - Ghost Trapper": WOLLocationData("Random Encounters H", "Random Encounters H"),
    "Rufus' Gifts - Gift 1": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Rufus' Gifts - Gift 2": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Rufus' Gifts - Gift 3": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Rufus' Gifts - Gift 4": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Rufus' Gifts - Gift 5": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Opened Charred Locket": WOLLocationData("Miscellaneous", "Miscellaneous"),
    "Magic-Infused Leaf Crafting - 3 Leaves": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Magic-Infused Leaf Crafting - 5 Leaves": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Magic-Infused Leaf Crafting - 7 Leaves": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Spider Part Crafting - 4 Piles": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Spider Part Crafting - 6 Piles": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Spider Part Crafting - 8 Piles": WOLLocationData("Miscellaneous", "Miscellaneous", is_dlc=True),
    "Leatherworkery Crafting - Level 1 (Hat)": WOLLocationData("Leatherworkery Crafting", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 1 (Pants)": WOLLocationData("Leatherworkery Crafting", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 1 (Boots)": WOLLocationData("Leatherworkery Crafting", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 1 (Bag)": WOLLocationData("Leatherworkery Crafting", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 1 (Gloves)": WOLLocationData("Leatherworkery Crafting", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 2 (Hat)": WOLLocationData("Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 2 (Pants)": WOLLocationData("Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 2 (Boots)": WOLLocationData("Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 2 (Bag)": WOLLocationData("Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 2 (Gloves)": WOLLocationData("Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Hat)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Pants)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Boots)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Bag)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Gloves)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Leatherworkery Crafting - Level 3 (Mallet)": WOLLocationData("Leatherworkery Crafting (Level 3)", "Leatherworkery Crafting"),
    "Master Cookery Crafting - Level 1 (Badge)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 1 (Skillet)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 1 (Spatula)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 2 (Collander)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 2 (Ladle)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 2 (Saucepan)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 3 (Kettle)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 3 (Shootin' Iron)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Master Cookery Crafting - Level 3 (Whisk)": WOLLocationData("Master Cookery Crafting", "Master Cookery Crafting"),
    "Progressive Loot - 3rd Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 6th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 9th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 12th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 15th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 18th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 21st Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 24th Grave Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 5th Army Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 10th Army Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 15th Army Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 5th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 7th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 9th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 11th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 13th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 15th El Vibrato Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 3rd Mining Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 6th Mining Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 9th Mining Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 5th Ranch Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 10th Ranch Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 15th Ranch Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 3rd Medical Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 6th Medical Container": WOLLocationData("Progressive Containers", "Progressive Containers"),
    "Progressive Loot - 9th Medical Container": WOLLocationData("Progressive Containers", "Progressive Containers")
}

location_name_to_id: Dict[str, int] = {name: base_id + index for index, name in enumerate(location_table)}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)