from typing import Dict, Set
import copy

#Note: Access paths do not always correlate to the in-game map regions
#Some map regions (e.g. C) have multiple possible initial access points that need to link back to the region for wandering
#Without map/entrance rando, many of these could be condensed into larger groups
basegame_region_table: Dict[str, Set[str]] = {
    "Menu": {"Your Family's Farm"},
    "Your Family's Farm": {"Dirtwater"},
    "Dirtwater": {"Map Region A", "Railroad Camp (East)", "Desert House", "Cavern Canyon", "The Potemkin Gang",
                  "Old Millinery", "Abandoned Pickle Factory", "The Daveyard", "Fort Cowardice",
                  "The Perfessor's House", "Rescue Mission", "Tony's Boots", "Murray's Curiosity & Bean",
                  "Grady's Fine Leather Goods", "Alexandria's Bookstore", "Fort Alldead", "Miscellaneous"},
    "Map Region A": {"Shaggy Dog Cave", "Silversmith's House", "Stearns Ranch", "Snakepit Mine", "The Daveyard",
                     "Buttonwillow's Store", "Fort Cowardice", "Wanderin' Sally's Camp", "Random Encounters A"},
    "Railroad Camp (East)": {"Map Region B", "Gustavson Gulch", "Buttonwillow's Store", "Railroad Camp (West)"},
    "Desert House": set(),
    "Cavern Canyon": set(),
    "The Daveyard": set(),
    "Fort Cowardice": set(),
    "Tony's Boots": set(),
    "Murray's Curiosity & Bean": set(),
    "Grady's Fine Leather Goods": set(),
    "Alexandria's Bookstore": set(),
    "Shaggy Dog Cave": set(),
    "Stearns Ranch": set(),
    "Snakepit Mine": set(),
    "Buttonwillow's Store": set(),
    "Wanderin' Sally's Camp": set(),
    "Random Encounters A": set(),
    "Gustavson Gulch": set(),
    "Silversmith's House": {"The Silver Plater"},
    "The Perfessor's House": {"Lost Dutch Oven Mine"},
    "Map Region B": {"Butterfield Ranch", "Kole Ridge Mine", "Dynamite Dan's", "Snake Spring", "Old Mission",
                     "Destroyed Campsite", "The Big Apple", "Random Encounters B"},
    "Butterfield Ranch": {"Kole Ridge Mine"},
    "Kole Ridge Mine": set(),
    "Dynamite Dan's": set(),
    "Snake Spring": set(),
    "Old Mission": set(),
    "Destroyed Campsite": {"Clown Campsite"},
    "The Big Apple": set(),
    "Random Encounters B": set(),
    "Clown Campsite": {"Circus", "Danny's Tannery"},
    "Danny's Tannery": set(),
    "Map Region C": {"Rescue Mission", "Fort Alldead", "Lazy-A Dude Ranch", "Humming Cave", "Circus",
                     "Random Encounters C"},
    "The Potemkin Gang": {"Map Region C"},
    "Old Millinery": {"Map Region C"},
    "Abandoned Pickle Factory": {"Map Region C"},
    "The Silver Plater": {"Map Region C"},
    "Lost Dutch Oven Mine": {"Map Region C"},
    "Rescue Mission": {"Map Region C", "Humming Cave"},
    "Humming Cave": {"Map Region C"},
    "Fort Alldead": {"Map Region C"},
    "Lazy-A Dude Ranch": {"Map Region C"},
    "Circus": {"Map Region C", "Circus (Inside)"},
    "Circus (Inside)": {"Danny's Tannery"},
    "Random Encounters C": set(),
    "Railroad Camp (West)": {"Map Region E", "Breadwood", "Roy Bean's House", "Necromancer's Tower", "Frisco"},
    "Necromancer's Tower": set(),
    "Breadwood": {"Map Region D", "Ghostwood", "Postal Way Station", "Soupstock Lode", "Ol' Schmaltz Brewery",
                  "Baker Boys' Hideout", "Military Cemetery", "Alexandria Ranch", "Petting Cemetery"},
    "Map Region D": {"Alexandria Ranch", "Curious Abandoned Well", "Curious Copse", "Fort Treason", "Ghostwood",
                     "Jumbleneck Mine", "Military Cemetery", "Random Encounters D"},
    "Ghostwood": set(),
    "Soupstock Lode": set(),
    "Ol' Schmaltz Brewery": set(),
    "Baker Boys' Hideout": set(),
    "Curious Copse": set(),
    "Fort Treason": set(),
    "Random Encounters D": set(),
    "Jumbleneck Mine": {"Jumbleneck Mine (Inside)"},
    "Jumbleneck Mine (Inside)": set(),
    "Curious Abandoned Well": {"Curious Abandoned Well Facility"},
    "Curious Abandoned Well Facility": set(),
    "Postal Way Station": {"Chuck's House", "Reboot Hill"},
    "Chuck's House": {"Chuck's House Cellar"},
    "Chuck's House Cellar": set(),
    "Military Cemetery": {"Fort Memoriam"},
    "Fort Memoriam": set(),
    "Alexandria Ranch": {"Fort Treason", "Alexandria Ranch Vault"},
    "Alexandria Ranch Vault": set(),
    "Map Region E": {"Reboot Hill", "Hellstrom Ranch", "Fort Memoriam", "Soupstock Lode", "The West Pole",
                     "The Great Garbanzo's Hideout", "The Old Medicine Show", "Random Encounters E"},
    "Reboot Hill": {"Hellstrom Ranch"},
    "Hellstrom Ranch": set(),
    "The West Pole": set(),
    "The Great Garbanzo's Hideout": set(),
    "The Old Medicine Show": set(),
    "Random Encounters E": set(),
    "Roy Bean's House": {"Map Region F", "Jelly Bean Thieves' Hideout", "Ol' Granddad", "Shroomcave"},
    "Jelly Bean Thieves' Hideout": set(),
    "Ol' Granddad": set(),
    "Shroomcave": set(),
    "Map Region F": {"Buffalo Pile", "Petting Cemetery", "Kellogg Ranch", "Madness Maw Mine",
                     "Roy Bean's House", "Fort of Darkness", "Random Encounters F"},
    "Buffalo Pile": set(),
    "Petting Cemetery": {"Buffalo Pile", "Fort of Darkness", "Kellogg Ranch"},
    "Kellogg Ranch": set(),
    "Madness Maw Mine": {"El Vibrato Outpost (MMM)"},
    "El Vibrato Outpost (MMM)": set(),
    "Fort of Darkness": set(),
    "Random Encounters F": set(),
    "Frisco": {"Map Region G", "Wasco's Comedy Shack", "Roy Bean's House", "Dr. Morton's House"},
    "Map Region G": {"Abandoned Mine", "Fort Unnecessary", "Last Custard Stand", "Jeweler's Cabin",
                     "Random Encounters G"},
    "Wasco's Comedy Shack": set(),
    "Abandoned Mine": {"Abandoned Mine (Inside)"},
    "Abandoned Mine (Inside)": set(),
    "Fort Unnecessary": {"Jeweler's Cabin", "Alamo Rent-A-Mule"},
    "Last Custard Stand": set(),
    "Jeweler's Cabin": set(),
    "Random Encounters G": set(),
    "Dr. Morton's House": {"Old Cave", "Abandoned Mine"},
    "Old Cave": set(),
    "Alamo Rent-A-Mule": {"Map Region H", "Deepest Delve Mine"},
    "Map Region H": {"Alamo Rent-A-Mule", "Curious False Mountain", "Curious Flat Plain", "Deepest Delve Mine",
                     "Halloway's Hideaway", "Moonshine Still", "Olive Garden's Homestead", "Random Encounters H"},
    "Deepest Delve Mine": {"Deepest Delve Mine (Elevator Fixed)"},
    "Deepest Delve Mine (Elevator Fixed)": set(),
    "Curious False Mountain": set(),
    "Curious Flat Plain": set(),
    "Halloway's Hideaway": set(),
    "Moonshine Still": set(),
    "Olive Garden's Homestead": set(),
    "Random Encounters H": set(),
    "Miscellaneous": {"Leatherworkery Crafting", "Master Cookery Crafting", "Progressive Containers"},
    "Leatherworkery Crafting": {"Leatherworkery Crafting (Level 2)", "Leatherworkery Crafting (Level 3)"},
    "Leatherworkery Crafting (Level 2)": set(),
    "Leatherworkery Crafting (Level 3)": set(),
    "Master Cookery Crafting": set(),
    "Progressive Containers": set()
}

dlc_region_table: Dict[str, Set[str]] = {
    "Gun Manor": {"Gun Manor Hedge Maze", "Gun Manor Carriage House", "Gun Manor Visitor Center",
                  "Gun Manor First Floor"},
    "Gun Manor Hedge Maze": {"Gun Manor Cellar"},
    "Gun Manor Carriage House": set(),
    "Gun Manor Visitor Center": set(),
    "Gun Manor Cellar": {"Gun Manor Laboratory"},
    "Gun Manor Laboratory": set(),
    "Gun Manor First Floor": {"Gun Manor Cellar", "Gun Manor Parlor", "Gun Manor Kitchen", "Gun Manor Dining Room",
                              "Gun Manor Second Floor"},
    "Gun Manor Parlor": set(),
    "Gun Manor Kitchen": {"Gun Manor Larder", "Gun Manor Pantry"},
    "Gun Manor Larder": set(),
    "Gun Manor Pantry": set(),
    "Gun Manor Dining Room": set(),
    "Gun Manor Second Floor": {"Gun Manor Library", "Gun Manor Art Gallery", "Gun Manor Restroom",
                               "Gun Manor Guest Rooms", "Gun Manor Third Floor"},
    "Gun Manor Library": set(),
    "Gun Manor Art Gallery": set(),
    "Gun Manor Restroom": set(),
    "Gun Manor Guest Rooms": set(),
    "Gun Manor Third Floor": {"Mr. Gun's Manliness Room", "Mrs. Gun's Room", "Gun Manor Music Room",
                              "Gun Manor Children's Quarters"},
    "Mr. Gun's Manliness Room": {"Gun Manor Billiards Room", "Mr. Gun's Bowling Room", "Mr. Gun's Trophy Room"},
    "Gun Manor Billiards Room": {"Gun Manor Belfry"},
    "Gun Manor Belfry": set(),
    "Mr. Gun's Bowling Room": set(),
    "Mr. Gun's Trophy Room": set(),
    "Mrs. Gun's Room": set(),
    "Gun Manor Music Room": set(),
    "Gun Manor Children's Quarters": {"Gun Manor Nursery", "Gun Manor Toddler's Room", "Gun Manor Tween Room"},
    "Gun Manor Nursery": set(),
    "Gun Manor Toddler's Room": set(),
    "Gun Manor Tween Room": set()
}

combined_dlc_region_table = copy.deepcopy(basegame_region_table | dlc_region_table)
combined_dlc_region_table["Dirtwater"].add("Gun Manor")