item_groups: dict[str, set[str]] = {
    "Skills": {
        "Sword",
        "Double Jump",
        "Regenerate",
        "Bow",
        "Dash",
        "Bash",
        "Grapple",
        "Glide",
        "Flap",
        "Grenade",
        "Flash",
        "Water Dash",
        "Burrow",
        "Launch",
        "Clean Water",
        "Water Breath",
        "Hammer",
        "Sentry",
        "Shuriken",
        "Spear",
        "Blaze",
    },
    "Collectibles": {
        "Health Fragment",
        "Energy Fragment",
        "Keystone",
        "Gorlek Ore",
        "Shard Slot",
        "Ancestral Light 1",
        "Ancestral Light 2",
    },
    "Spirit Light": {
        "1 Spirit Light",
        "50 Spirit Light",
        "100 Spirit Light",
        "200 Spirit Light",
    },
    "Shards": {
        "Overcharge",
        "Triple Jump",
        "Wingclip",
        "Bounty",
        "Swap",
        "Magnet",
        "Splinter",
        "Reckless",
        "Quickshot",
        "Resilience",
        "Light Harvest",
        "Vitality",
        "Life Harvest",
        "Energy Harvest",
        "Energy (Shard)",
        "Life Pact",
        "Last Stand",
        "Sense",
        "Ultra Bash",
        "Ultra Grapple",
        "Overflow",
        "Thorn",
        "Catalyst",
        "Turmoil",
        "Sticky",
        "Finesse",
        "Spirit Surge",
        "Lifeforce",
        "Deflector",
        "Fracture",
        "Arcing",
    },
    "Teleporters": {
        "Midnight Burrows TP",
        "Howl's Den TP",
        "Central Luma TP",
        "Mouldwood Depths TP",
        "Wellspring TP",
        "Baur's Reach TP",
        "Kwolok's Hollow TP",
        "Woods Entrance TP",
        "Woods Exit TP",
        "Feeding Grounds TP",
        "Central Wastes TP",
        "Outer Ruins TP",
        "Willow's End TP",
        "Inkwater Marsh TP",
        "Glades TP",
    },
    "Extra Teleporters": {
        "Luma Boss TP",
        "Inner Ruins TP",
        "Shriek TP",
    },
    "Weapon Upgrades": {
        "Exploding Spear",
        "Hammer Shockwave",
        "Static Shuriken",
        "Charge Blaze",
        "Rapid Sentry",
    },
    "Bonus": {
        "Health Regeneration",
        "Energy Regeneration",
        "Extra Double Jump",
        "Extra Air Dash",
        "Blaze Efficiency",
        "Spear Efficiency",
        "Shuriken Efficiency",
        "Sentry Efficiency",
        "Bow Efficiency",
        "Regenerate Efficiency",
        "Flash Efficiency",
        "Grenade Efficiency",
    },
    "Bonus+": {
        "Rapid Sword",
        "Rapid Hammer",
        "Rapid Spear",
        "Rapid Grenade",
        "Quickshot Upgrade",
        "Rapid Regenerate",
        "Melting Bow",
        "Melting Blaze",
        "Melting Sword",
        "Melting Hammer",
        "Melting Spear",
        "Melting Shuriken",
        "Uncharged Bashnades",
        "Extra Grenade",
        "Splinter Grenade",
        "Unlimited Sentries",
        "Sentry Burst Upgrade",
        "Sentry Fire Rate",
        "Extra Shurikens",
        "Splinter Shurikens",
        "Bashable Shurikens",
    },
    "Skill Upgrades": {
        "Jumpgrade",
        "Skill Velocity",
    },
    # Aliases TODO: verify the game names
    "Spirit Edge": {"Sword"},
    "Spirit Arc": {"Bow"},
    "Spirit Smash": {"Hammer"},
    "Spirit Star": {"Shuriken"},
    "Spirit Spear": {"Spear"},
    "Light Burst": {"Grenade"},
    "Swim Dash": {"Water Dash"},
    "Health": {"Health Fragment"},
    "Energy": {"Energy Fragment"},
    "Ore": {"Gorlek Ore"},
    "Key": {"Keystone"},
    "Heal": {"Regenerate"},
    "Light": {"Flash"},
    "Poison": {"Clean Water"},
}
